import { ref as $ref, atom as $atom } from 'reaxtor-falcor-json-graph';

export function toolbar(workbookId, viewId) {
    const prefix = `workbooksById['${workbookId}'].viewsById['${viewId}']`;
    return {
        toolbar: {
            visible: true,
            length: 6,
            0: $ref(`${prefix}.toolbarItems[0]`),
            1: $ref(`${prefix}.toolbarItems[1]`),
            2: $ref(`${prefix}.toolbarItems[2]`),
            3: $ref(`${prefix}.toolbarItems[3]`),
            4: $ref(`${prefix}.toolbarItems[4]`),
            5: $ref(`${prefix}.toolbarItems[5]`),
        },
        toolbarItems: {
            length: 6,
            0: {
                name: 'Browser Controls',
                length: 2,
                0: $ref(`${prefix}.toolsById['open-workbook']`),
                1: $ref(`${prefix}.toolsById['fullscreen-workbook']`),
            },
            1: {
                name: 'View Controls',
                length: 3,
                0: $ref(`${prefix}.toolsById['zoom-in']`),
                1: $ref(`${prefix}.toolsById['zoom-out']`),
                2: $ref(`${prefix}.toolsById['center-camera']`),
            },
            2: {
                name: 'Layout Controls',
                length: 2,
                0: $ref(`${prefix}.toolsById['toggle-simulating']`),
                1: $ref(`${prefix}.toolsById['toggle-settings']`),
            },
            3: {
                name: 'Selection Controls',
                length: 2,
                0: $ref(`${prefix}.toolsById['toggle-select-nodes']`),
                1: $ref(`${prefix}.toolsById['toggle-window-nodes']`),
            },
            4: {
                name: 'Panel Controls',
                length: 6,
                0: $ref(`${prefix}.toolsById['toggle-histograms']`),
                1: $ref(`${prefix}.toolsById['toggle-inspector']`),
                2: $ref(`${prefix}.toolsById['toggle-timebar']`),
                3: $ref(`${prefix}.toolsById['toggle-exclusions']`),
                4: $ref(`${prefix}.toolsById['toggle-filters']`),
                5: $ref(`${prefix}.toolsById['toggle-sets']`),
            },
            5: {
                name: 'Workbook Controls',
                length: 3,
                0: $ref(`${prefix}.toolsById['fork-workbook']`),
                1: $ref(`${prefix}.toolsById['save-workbook']`),
                2: $ref(`${prefix}.toolsById['embed-workbook']`),
            },
        },
        toolsById: {
            'zoom-in': {
                id: 'zoom-in',
                name: 'Zoom in',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'zoom-out': {
                id: 'zoom-out',
                name: 'Zoom out',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'center-camera': {
                id: 'center-camera',
                name: 'Center view',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-simulating': {
                id: 'toggle-simulating',
                name: 'Toggle visual clustering',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-settings': {
                id: 'toggle-settings',
                name: 'Settings',
                panel: 'settings',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-select-nodes': {
                id: 'toggle-select-nodes',
                name: 'Select nodes',
                panel: 'histograms',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-window-nodes': {
                id: 'toggle-window-nodes',
                name: 'Data brush',
                panel: 'inspector',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-histograms': {
                id: 'toggle-histograms',
                name: 'Histograms',
                panel: 'histograms',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-inspector': {
                id: 'toggle-inspector',
                name: 'Data Inspector',
                panel: 'inspector',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-timebar': {
                id: 'toggle-timebar',
                name: 'Timebar',
                panel: 'timebar',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-exclusions': {
                id: 'toggle-exclusions',
                name: 'Exclusions',
                panel: 'exclusions',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-filters': {
                id: 'toggle-filters',
                name: 'Filters',
                panel: 'filters',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'toggle-sets': {
                id: 'toggle-sets',
                name: 'Sets',
                panel: 'sets',
                beta: true,
                iFrame: false,
                selected: false,
            },
            'open-workbook': {
                id: 'open-workbook',
                name: 'Open in New Tab',
                beta: false,
                iFrame: true,
                selected: false,
            },
            'fullscreen-workbook': {
                id: 'fullscreen-workbook',
                name: 'Expand to fullscreen',
                beta: false,
                iFrame: true,
                selected: false,
            },
            'fork-workbook': {
                id: 'fork-workbook',
                name: 'Copy Workbook',
                beta: false,
                iFrame: false,
                selected: false,
            },
            'save-workbook': {
                id: 'save-workbook',
                name: 'Save Workbook',
                beta: true,
                iFrame: false,
                selected: false,
            },
            'embed-workbook': {
                id: 'embed-workbook',
                name: 'Share Workbook',
                beta: false,
                iFrame: false,
                selected: false,
            },
        }
    };
}
