module.exports = (function() {
  /*
   * Generated by PEG.js 0.8.0.
   *
   * http://pegjs.majda.cz/
   */

  function peg$subclass(child, parent) {
    function ctor() { this.constructor = child; }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor();
  }

  function SyntaxError(message, expected, found, offset, line, column) {
    this.message  = message;
    this.expected = expected;
    this.found    = found;
    this.offset   = offset;
    this.line     = line;
    this.column   = column;

    this.name     = "SyntaxError";
  }

  peg$subclass(SyntaxError, Error);

  function parse(input) {
    var options = arguments.length > 1 ? arguments[1] : {},

        peg$FAILED = {},

        peg$startRuleIndices = { start: 0 },
        peg$startRuleIndex   = 0,

        peg$consts = [
          { type: "other", description: "type name" },
          { type: "other", description: "type" },
          peg$FAILED,
          [],
          null,
          { type: "other", description: "cast" },
          function(value, type_name) {
              return {
                type: 'CastExpression',
                value: value,
                type_name: type_name
              };
            },
          function(operator, argument) {
                return {
                  type: 'UnaryExpression',
                  operator: operator,
                  argument: argument,
                  fixity: 'prefix'
                };
              },
          function(first, rest) { return buildBinaryPredicate(first, rest); },
          { type: "other", description: "limit" },
          function(limit) { return { type: 'Limit', value: limit } },
          { type: "other", description: "WHERE clause" },
          { type: "other", description: "now" },
          { type: "other", description: "literal" },
          function(element) {
                  return optionalList(element);
                },
          function(first, rest) { return Array.prototype.concat.apply(first, rest); },
          function() {
                return {
                  type: 'ListExpression',
                  elements: []
                }
              },
          function(elements) {
                return {
                  type: 'ListExpression',
                  elements: elements
                }
              },
          void 0,
          function(name) { return { type: 'FunctionIdentifier', name: name.name }; },
          { type: "other", description: "function call" },
          function(callee) {
              return {
                type: 'FunctionCall',
                callee: callee,
                arguments: []
              };
            },
          function(callee, elements) {
              return {
                type: 'FunctionCall',
                callee: callee,
                arguments: elements
              };
            },
          function(expression) { return expression; },
          /^[0-9]/,
          { type: "class", value: "[0-9]", description: "[0-9]" },
          /^[1-9]/,
          { type: "class", value: "[1-9]", description: "[1-9]" },
          "0",
          { type: "literal", value: "0", description: "\"0\"" },
          function() {
              return { type: "Literal", dataType: 'integer', value: 0 };
            },
          function() {
              return { type: "Literal", dataType: 'integer', value: parseInt(text()) };
            },
          "e",
          { type: "literal", value: "e", description: "\"e\"" },
          /^[+\-]/,
          { type: "class", value: "[+\\-]", description: "[+\\-]" },
          function() {
                return { type: "Literal", dataType: 'float', value: parseFloat(text()) };
              },
          function() {
                return { type: "Literal", dataType: 'integer', value: parseFloat(text()) };
              },
          /^[0-9a-f]/i,
          { type: "class", value: "[0-9a-f]i", description: "[0-9a-f]i" },
          "0x",
          { type: "literal", value: "0x", description: "\"0x\"" },
          function(digits) {
                return { type: "Literal", dataType: 'integer', value: parseInt(digits, 16) };
               },
          { type: "any", description: "any character" },
          /^[A-Za-z_]/,
          { type: "class", value: "[A-Za-z_]", description: "[A-Za-z_]" },
          { type: "other", description: "identifier" },
          function(first, rest) {
                return {
                  type: "Identifier",
                  name: first + rest.join("")
                };
              },
          function(name) { return name; },
          { type: "other", description: "number" },
          function(literal) {
                return literal;
              },
          { type: "other", description: "numeric constant" },
          "\\",
          { type: "literal", value: "\\", description: "\"\\\\\"" },
          { type: "other", description: "identifier with brackets" },
          function(chars) {
                return {
                  type: "Identifier",
                  name: chars.join("")
                };
              },
          function() { return text(); },
          function(sequence) { return sequence; },
          "\"",
          { type: "literal", value: "\"", description: "\"\\\"\"" },
          "'",
          { type: "literal", value: "'", description: "\"'\"" },
          { type: "other", description: "string" },
          function(chars) {
                return { type: "Literal", dataType: 'string', value: chars.join("") };
              },
          function() { return ""; },
          function() { return "\0"; },
          "b",
          { type: "literal", value: "b", description: "\"b\"" },
          function() { return "\b";   },
          "f",
          { type: "literal", value: "f", description: "\"f\"" },
          function() { return "\f";   },
          "n",
          { type: "literal", value: "n", description: "\"n\"" },
          function() { return "\n";   },
          "r",
          { type: "literal", value: "r", description: "\"r\"" },
          function() { return "\r";   },
          "t",
          { type: "literal", value: "t", description: "\"t\"" },
          function() { return "\t";   },
          "v",
          { type: "literal", value: "v", description: "\"v\"" },
          function() { return "\x0B"; },
          "x",
          { type: "literal", value: "x", description: "\"x\"" },
          "u",
          { type: "literal", value: "u", description: "\"u\"" },
          function(digits) {
                return String.fromCharCode(parseInt(digits, 16));
              },
          { type: "other", description: "comment" },
          ".",
          { type: "literal", value: ".", description: "\".\"" },
          ",",
          { type: "literal", value: ",", description: "\",\"" },
          ":",
          { type: "literal", value: ":", description: "\":\"" },
          ";",
          { type: "literal", value: ";", description: "\";\"" },
          "--",
          { type: "literal", value: "--", description: "\"--\"" },
          "-",
          { type: "literal", value: "-", description: "\"-\"" },
          "+",
          { type: "literal", value: "+", description: "\"+\"" },
          "*",
          { type: "literal", value: "*", description: "\"*\"" },
          "/",
          { type: "literal", value: "/", description: "\"/\"" },
          "%",
          { type: "literal", value: "%", description: "\"%\"" },
          "~",
          { type: "literal", value: "~", description: "\"~\"" },
          "(",
          { type: "literal", value: "(", description: "\"(\"" },
          ")",
          { type: "literal", value: ")", description: "\")\"" },
          "[",
          { type: "literal", value: "[", description: "\"[\"" },
          "]",
          { type: "literal", value: "]", description: "\"]\"" },
          "||",
          { type: "literal", value: "||", description: "\"||\"" },
          "<",
          { type: "literal", value: "<", description: "\"<\"" },
          ">",
          { type: "literal", value: ">", description: "\">\"" },
          "<=",
          { type: "literal", value: "<=", description: "\"<=\"" },
          ">=",
          { type: "literal", value: ">=", description: "\">=\"" },
          "=",
          { type: "literal", value: "=", description: "\"=\"" },
          "==",
          { type: "literal", value: "==", description: "\"==\"" },
          "!=",
          { type: "literal", value: "!=", description: "\"!=\"" },
          "<>",
          { type: "literal", value: "<>", description: "\"<>\"" },
          "\n",
          { type: "literal", value: "\n", description: "\"\\n\"" },
          /^[^\n]/,
          { type: "class", value: "[^\\n]", description: "[^\\n]" },
          "//",
          { type: "literal", value: "//", description: "\"//\"" },
          "/*",
          { type: "literal", value: "/*", description: "\"/*\"" },
          "*/",
          { type: "literal", value: "*/", description: "\"*/\"" },
          "",
          { type: "other", description: "null" },
          function() { return { type: "Literal", dataType: 'null', value: null }; },
          { type: "other", description: "boolean" },
          function() { return { type: "Literal", dataType: 'boolean', value: true  }; },
          function() { return { type: "Literal", dataType: 'boolean', value: false }; },
          { type: "other", description: "reserved word" },
          function(first, rest) { return buildBinaryExpression(first, rest); },
          { type: "other", description: "shift operator" },
          "<<",
          { type: "literal", value: "<<", description: "\"<<\"" },
          ">>",
          { type: "literal", value: ">>", description: "\">>\"" },
          { type: "other", description: "comparison" },
          { type: "other", description: "equality operator" },
          { type: "other", description: "whitespace" },
          "\t",
          { type: "literal", value: "\t", description: "\"\\t\"" },
          "\x0B",
          { type: "literal", value: "\x0B", description: "\"\\x0B\"" },
          "\f",
          { type: "literal", value: "\f", description: "\"\\f\"" },
          " ",
          { type: "literal", value: " ", description: "\" \"" },
          "\xA0",
          { type: "literal", value: "\xA0", description: "\"\\xA0\"" },
          "\uFEFF",
          { type: "literal", value: "\uFEFF", description: "\"\\uFEFF\"" },
          { type: "other", description: "line terminator" },
          /^[\n\r\u2028\u2029]/,
          { type: "class", value: "[\\n\\r\\u2028\\u2029]", description: "[\\n\\r\\u2028\\u2029]" },
          { type: "other", description: "end of line" },
          "\r\n",
          { type: "literal", value: "\r\n", description: "\"\\r\\n\"" },
          "\r",
          { type: "literal", value: "\r", description: "\"\\r\"" },
          "\u2028",
          { type: "literal", value: "\u2028", description: "\"\\u2028\"" },
          "\u2029",
          { type: "literal", value: "\u2029", description: "\"\\u2029\"" },
          { type: "other", description: "postfix keyword" },
          function(argument, operator) {
                return {
                  type: 'UnaryExpression',
                  operator: operator,
                  argument: argument,
                  fixity: 'postfix'
                };
              },
          function(left, operator, right) {
                return {
                  type: 'BinaryPredicate',
                  operator: operator,
                  left: left,
                  right: right
                };
              },
          function(left, operator, right) { return {
                   type: 'BinaryPredicate',
                   operator: operator,
                   left: left,
                   right: right
                };
              },
          function(left, operator) { return buildBinaryPredicate(first, rest); },
          function(value, low, high) {
                // TODO: use negated
                return {
                    type: 'BetweenPredicate',
                    value: value,
                    start: low,
                    stop:  high
                };
              },
          { type: "other", description: "text comparison" },
          function(value, operator, like, escapeChar) { return {
                  type: 'LikePredicate',
                  operator: operator,
                  left: value,
                  right: like,
                  escapeChar: escapeChar
                };
              },
          function(value, operator, like) { return {
                  type: 'LikePredicate',
                  operator: operator,
                  left: value,
                  right: like
                };
              },
          { type: "other", description: "regex expression" },
          function(value, operator, matcher) {
                return {
                  type: 'RegexPredicate',
                  operator: operator,
                  left: value,
                  right: matcher
                };
              },
          { type: "other", description: "not" },
          function(operator, argument) {
                return {
                  type: 'NotExpression',
                  operator: operator,
                  value: argument
                };
              },
          function(property) { return { name: property }; },
          function(first, rest) {
                return buildTree(first, rest, function(result, element) {
                  return {
                    type:     'MemberAccess',
                    object:   result,
                    name:     element.name
                  };
                });
              },
          { type: "other", description: "prefix operator" },
          function(operator, argument) {
              return {
                type: 'UnaryExpression',
                operator: operator,
                argument: argument,
                fixity: 'prefix'
              };
            },
          { type: "other", description: "multiplicative operator" },
          /^[A-Za-z0-9_:]/,
          { type: "class", value: "[A-Za-z0-9_:]", description: "[A-Za-z0-9_:]" },
          function(str) { return str.join(''); },
          function(c) { return { column: c[2], graph_namespace: c[1] }; },
          function(c) { return { column: c }; },
          function(gcn) { return gcn[1]; },
          "?",
          { type: "literal", value: "?", description: "\"?\"" },
          "now",
          { type: "literal", value: "now", description: "\"now\"" },
          "abort",
          { type: "literal", value: "ABORT", description: "\"ABORT\"" },
          "action",
          { type: "literal", value: "ACTION", description: "\"ACTION\"" },
          "add",
          { type: "literal", value: "ADD", description: "\"ADD\"" },
          "after",
          { type: "literal", value: "AFTER", description: "\"AFTER\"" },
          "all",
          { type: "literal", value: "ALL", description: "\"ALL\"" },
          "alter",
          { type: "literal", value: "ALTER", description: "\"ALTER\"" },
          "analyze",
          { type: "literal", value: "ANALYZE", description: "\"ANALYZE\"" },
          "and",
          { type: "literal", value: "AND", description: "\"AND\"" },
          "array",
          { type: "literal", value: "ARRAY", description: "\"ARRAY\"" },
          "as",
          { type: "literal", value: "AS", description: "\"AS\"" },
          "asc",
          { type: "literal", value: "ASC", description: "\"ASC\"" },
          "attach",
          { type: "literal", value: "ATTACH", description: "\"ATTACH\"" },
          "autoincrement",
          { type: "literal", value: "AUTOINCREMENT", description: "\"AUTOINCREMENT\"" },
          "before",
          { type: "literal", value: "BEFORE", description: "\"BEFORE\"" },
          "begin",
          { type: "literal", value: "BEGIN", description: "\"BEGIN\"" },
          "between",
          { type: "literal", value: "BETWEEN", description: "\"BETWEEN\"" },
          "by",
          { type: "literal", value: "BY", description: "\"BY\"" },
          "cascade",
          { type: "literal", value: "CASCADE", description: "\"CASCADE\"" },
          "case",
          { type: "literal", value: "CASE", description: "\"CASE\"" },
          "cast",
          { type: "literal", value: "CAST", description: "\"CAST\"" },
          "check",
          { type: "literal", value: "CHECK", description: "\"CHECK\"" },
          "collate",
          { type: "literal", value: "COLLATE", description: "\"COLLATE\"" },
          "column",
          { type: "literal", value: "COLUMN", description: "\"COLUMN\"" },
          "commit",
          { type: "literal", value: "COMMIT", description: "\"COMMIT\"" },
          "conflict",
          { type: "literal", value: "CONFLICT", description: "\"CONFLICT\"" },
          "constraint",
          { type: "literal", value: "CONSTRAINT", description: "\"CONSTRAINT\"" },
          "create",
          { type: "literal", value: "CREATE", description: "\"CREATE\"" },
          "cross",
          { type: "literal", value: "CROSS", description: "\"CROSS\"" },
          "database",
          { type: "literal", value: "DATABASE", description: "\"DATABASE\"" },
          "default",
          { type: "literal", value: "DEFAULT", description: "\"DEFAULT\"" },
          "deferrable",
          { type: "literal", value: "DEFERRABLE", description: "\"DEFERRABLE\"" },
          "deferred",
          { type: "literal", value: "DEFERRED", description: "\"DEFERRED\"" },
          "delete",
          { type: "literal", value: "DELETE", description: "\"DELETE\"" },
          "desc",
          { type: "literal", value: "DESC", description: "\"DESC\"" },
          "detach",
          { type: "literal", value: "DETACH", description: "\"DETACH\"" },
          "distinct",
          { type: "literal", value: "DISTINCT", description: "\"DISTINCT\"" },
          "drop",
          { type: "literal", value: "DROP", description: "\"DROP\"" },
          { type: "literal", value: "E", description: "\"E\"" },
          "each",
          { type: "literal", value: "EACH", description: "\"EACH\"" },
          "else",
          { type: "literal", value: "ELSE", description: "\"ELSE\"" },
          "end",
          { type: "literal", value: "END", description: "\"END\"" },
          "escape",
          { type: "literal", value: "ESCAPE", description: "\"ESCAPE\"" },
          "except",
          { type: "literal", value: "EXCEPT", description: "\"EXCEPT\"" },
          "exclusive",
          { type: "literal", value: "EXCLUSIVE", description: "\"EXCLUSIVE\"" },
          "exists",
          { type: "literal", value: "EXISTS", description: "\"EXISTS\"" },
          "explain",
          { type: "literal", value: "EXPLAIN", description: "\"EXPLAIN\"" },
          "fail",
          { type: "literal", value: "FAIL", description: "\"FAIL\"" },
          "false",
          { type: "literal", value: "FALSE", description: "\"FALSE\"" },
          "for",
          { type: "literal", value: "FOR", description: "\"FOR\"" },
          "foreign",
          { type: "literal", value: "FOREIGN", description: "\"FOREIGN\"" },
          "from",
          { type: "literal", value: "FROM", description: "\"FROM\"" },
          "glob",
          { type: "literal", value: "GLOB", description: "\"GLOB\"" },
          "group",
          { type: "literal", value: "GROUP", description: "\"GROUP\"" },
          "having",
          { type: "literal", value: "HAVING", description: "\"HAVING\"" },
          "if",
          { type: "literal", value: "IF", description: "\"IF\"" },
          "ignore",
          { type: "literal", value: "IGNORE", description: "\"IGNORE\"" },
          "ilike",
          { type: "literal", value: "ILIKE", description: "\"ILIKE\"" },
          "immediate",
          { type: "literal", value: "IMMEDIATE", description: "\"IMMEDIATE\"" },
          "in",
          { type: "literal", value: "IN", description: "\"IN\"" },
          "index",
          { type: "literal", value: "INDEX", description: "\"INDEX\"" },
          "indexed",
          { type: "literal", value: "INDEXED", description: "\"INDEXED\"" },
          "infinity",
          { type: "literal", value: "INFINITY", description: "\"INFINITY\"" },
          "initially",
          { type: "literal", value: "INITIALLY", description: "\"INITIALLY\"" },
          "inner",
          { type: "literal", value: "INNER", description: "\"INNER\"" },
          "insert",
          { type: "literal", value: "INSERT", description: "\"INSERT\"" },
          "instead",
          { type: "literal", value: "INSTEAD", description: "\"INSTEAD\"" },
          "integer",
          { type: "literal", value: "INTEGER", description: "\"INTEGER\"" },
          "intersect",
          { type: "literal", value: "INTERSECT", description: "\"INTERSECT\"" },
          "into",
          { type: "literal", value: "INTO", description: "\"INTO\"" },
          "is",
          { type: "literal", value: "IS", description: "\"IS\"" },
          "isnull",
          { type: "literal", value: "ISNULL", description: "\"ISNULL\"" },
          "join",
          { type: "literal", value: "JOIN", description: "\"JOIN\"" },
          "key",
          { type: "literal", value: "KEY", description: "\"KEY\"" },
          "left",
          { type: "literal", value: "LEFT", description: "\"LEFT\"" },
          "like",
          { type: "literal", value: "LIKE", description: "\"LIKE\"" },
          "limit",
          { type: "literal", value: "LIMIT", description: "\"LIMIT\"" },
          "match",
          { type: "literal", value: "MATCH", description: "\"MATCH\"" },
          "nan",
          { type: "literal", value: "NaN", description: "\"NaN\"" },
          "natural",
          { type: "literal", value: "NATURAL", description: "\"NATURAL\"" },
          "no",
          { type: "literal", value: "NO", description: "\"NO\"" },
          "not",
          { type: "literal", value: "NOT", description: "\"NOT\"" },
          "notnull",
          { type: "literal", value: "NOTNULL", description: "\"NOTNULL\"" },
          "null",
          { type: "literal", value: "NULL", description: "\"NULL\"" },
          "number",
          { type: "literal", value: "NUMBER", description: "\"NUMBER\"" },
          "of",
          { type: "literal", value: "OF", description: "\"OF\"" },
          "offset",
          { type: "literal", value: "OFFSET", description: "\"OFFSET\"" },
          "on",
          { type: "literal", value: "ON", description: "\"ON\"" },
          "or",
          { type: "literal", value: "OR", description: "\"OR\"" },
          "order",
          { type: "literal", value: "ORDER", description: "\"ORDER\"" },
          "outer",
          { type: "literal", value: "OUTER", description: "\"OUTER\"" },
          "plan",
          { type: "literal", value: "PLAN", description: "\"PLAN\"" },
          "pragma",
          { type: "literal", value: "PRAGMA", description: "\"PRAGMA\"" },
          "primary",
          { type: "literal", value: "PRIMARY", description: "\"PRIMARY\"" },
          "query",
          { type: "literal", value: "QUERY", description: "\"QUERY\"" },
          "raise",
          { type: "literal", value: "RAISE", description: "\"RAISE\"" },
          "references",
          { type: "literal", value: "REFERENCES", description: "\"REFERENCES\"" },
          "regexp",
          { type: "literal", value: "REGEXP", description: "\"REGEXP\"" },
          "reindex",
          { type: "literal", value: "REINDEX", description: "\"REINDEX\"" },
          "release",
          { type: "literal", value: "RELEASE", description: "\"RELEASE\"" },
          "rename",
          { type: "literal", value: "RENAME", description: "\"RENAME\"" },
          "replace",
          { type: "literal", value: "REPLACE", description: "\"REPLACE\"" },
          "restrict",
          { type: "literal", value: "RESTRICT", description: "\"RESTRICT\"" },
          "rollback",
          { type: "literal", value: "ROLLBACK", description: "\"ROLLBACK\"" },
          "row",
          { type: "literal", value: "ROW", description: "\"ROW\"" },
          "savepoint",
          { type: "literal", value: "SAVEPOINT", description: "\"SAVEPOINT\"" },
          "select",
          { type: "literal", value: "SELECT", description: "\"SELECT\"" },
          "set",
          { type: "literal", value: "SET", description: "\"SET\"" },
          "similar",
          { type: "literal", value: "SIMILAR", description: "\"SIMILAR\"" },
          "string",
          { type: "literal", value: "STRING", description: "\"STRING\"" },
          "table",
          { type: "literal", value: "TABLE", description: "\"TABLE\"" },
          "temp",
          { type: "literal", value: "TEMP", description: "\"TEMP\"" },
          "temporary",
          { type: "literal", value: "TEMPORARY", description: "\"TEMPORARY\"" },
          "then",
          { type: "literal", value: "THEN", description: "\"THEN\"" },
          "to",
          { type: "literal", value: "TO", description: "\"TO\"" },
          "transaction",
          { type: "literal", value: "TRANSACTION", description: "\"TRANSACTION\"" },
          "trigger",
          { type: "literal", value: "TRIGGER", description: "\"TRIGGER\"" },
          "true",
          { type: "literal", value: "TRUE", description: "\"TRUE\"" },
          "union",
          { type: "literal", value: "UNION", description: "\"UNION\"" },
          "unique",
          { type: "literal", value: "UNIQUE", description: "\"UNIQUE\"" },
          "update",
          { type: "literal", value: "UPDATE", description: "\"UPDATE\"" },
          "using",
          { type: "literal", value: "USING", description: "\"USING\"" },
          "vacuum",
          { type: "literal", value: "VACUUM", description: "\"VACUUM\"" },
          "values",
          { type: "literal", value: "VALUES", description: "\"VALUES\"" },
          "view",
          { type: "literal", value: "VIEW", description: "\"VIEW\"" },
          "virtual",
          { type: "literal", value: "VIRTUAL", description: "\"VIRTUAL\"" },
          "when",
          { type: "literal", value: "WHEN", description: "\"WHEN\"" },
          "where",
          { type: "literal", value: "WHERE", description: "\"WHERE\"" }
        ],

        peg$bytecode = [
          peg$decode("7)"),
          peg$decode("87\u0108*/ \"7\xDE*) \"7\xEF*# \"7\xA49*\" 3 "),
          peg$decode("8! #7!+&$,#&7!\"\"\" \"+\x8B$!7`+7$75+-%7a+#%'#%$## \"$\"# \"\"# \"*V \"!7`+K$75+A%7V+7%75+-%7a+#%'%%$%# \"$$# \"$## \"$\"# \"\"# \"*# \" $+#%'\"%$\"# \"\"# \"9*\" 3!"),
          peg$decode("8!7\xAF+\x8D$7\x84+\x83%7`+y%7\x84+o%7)+e%7\x84+[%7\xA5+Q%7\x84+G%7\"+=%7\x84+3%7a+)%4+6&+\"&\"%$+# \"$*# \"$)# \"$(# \"$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \"9*\" 3%"),
          peg$decode("!7\xEC+=$7\x84+3%7$+)%4#6'#\"\" %$## \"$\"# \"\"# \"*# \"7"),
          peg$decode("!7$+\x8D$ #!7\x84+A$7\xA3+7%7\x84+-%7$+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x84+A$7\xA3+7%7\x84+-%7$+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \""),
          peg$decode("!7%+\x8D$ #!7\x84+A$7\xF3+7%7\x84+-%7%+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x84+A$7\xF3+7%7\x84+-%7%+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \""),
          peg$decode("8!7\xE7+<$7\x84+2%7)+(%4#6*#! %$## \"$\"# \"\"# \"9*\" 3)"),
          peg$decode("87&9*\" 3+"),
          peg$decode("7'*# \"7("),
          peg$decode("87\x99*) \"7\x9A*# \"7\x9B9*\" 3,"),
          peg$decode("87?*A \"7@*; \"7F*5 \"7F*/ \"7v*) \"7w*# \"7*9*\" 3-"),
          peg$decode("!!7&+' 4!6.!! %+\x97$ #!7\x84+F$7V+<%7\x84+2%7&+(%4$6.$! %$$# \"$## \"$\"# \"\"# \",Q&!7\x84+F$7V+<%7\x84+2%7&+(%4$6.$! %$$# \"$## \"$\"# \"\"# \"\"+)%4\"6/\"\"! %$\"# \"\"# \""),
          peg$decode("!7`+;$7\x84+1%7a+'%4#60# %$## \"$\"# \"\"# \"*\xAD \"!7`+P$7\x84+F%7,+<%7\x84+2%7a+(%4%61%!\"%$%# \"$$# \"$## \"$\"# \"\"# \"*o \"!7`+d$7\x84+Z%7,+P%7\x84+F%7V+<%7\x84+2%7a+(%4'61'!$%$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \""),
          peg$decode("!!87x9*$$\"\" 2\"# \"+2$7=+(%4\"63\"! %$\"# \"\"# \""),
          peg$decode("8!7.+P$7\x84+F%7`+<%7\x84+2%7a+(%4%65%!$%$%# \"$$# \"$## \"$\"# \"\"# \"*p \"!7.+e$7\x84+[%7`+Q%7\x84+G%7,+=%7\x84+3%7a+)%4'66'\"&\"%$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \"9*\" 34"),
          peg$decode("7B*y \"7#*s \"7/*m \"7>*g \"7+*a \"!7`+P$7\x84+F%7(+<%7\x84+2%7a+(%4%67%!\"%$%# \"$$# \"$## \"$\"# \"\"# \"*# \"7-"),
          peg$decode("08\"\"1!39"),
          peg$decode("0:\"\"1!3;"),
          peg$decode("!.<\"\"2<3=+& 4!6>! %*D \"!72+9$ #71,#&71\"+'%4\"6?\" %$\"# \"\"# \""),
          peg$decode("/@\"\"1!3A"),
          peg$decode("!0B\"\"1!3C*# \" $+<$ #71+&$,#&71\"\"\" \"+#%'\"%$\"# \"\"# \""),
          peg$decode("!74+-$75+#%'\"%$\"# \"\"# \""),
          peg$decode("!73+S$7U+I% #71,#&71\"+7%76*# \" $+'%4$6D$ %$$# \"$## \"$\"# \"\"# \"*\x80 \"!7U+P$ #71+&$,#&71\"\"\" \"+7%76*# \" $+'%4#6D# %$## \"$\"# \"\"# \"*B \"!73+7$76*# \" $+'%4\"6E\" %$\"# \"\"# \""),
          peg$decode("0F\"\"1!3G"),
          peg$decode("!/H\"\"1\"3I+G$! #78+&$,#&78\"\"\" \"+! (%+(%4\"6J\"! %$\"# \"\"# \""),
          peg$decode("-\"\"1!3K"),
          peg$decode("0L\"\"1!3M"),
          peg$decode("7;*) \"7W*# \"71"),
          peg$decode("8!7;+;$ #7<,#&7<\"+)%4\"6O\"\"! %$\"# \"\"# \"9*\" 3N"),
          peg$decode("!!87x9*$$\"\" 2\"# \"+2$7=+(%4\"6P\"! %$\"# \"\"# \""),
          peg$decode("8!79+F$!87;*# \"719*$$\"\" 2\"# \"+(%4\"6R\"!!%$\"# \"\"# \"*Q \"!77+F$!87;*# \"719*$$\"\" 2\"# \"+(%4\"6R\"!!%$\"# \"\"# \"9*\" 3Q"),
          peg$decode("87\xD9*# \"7\xE99*\" 3S"),
          peg$decode(".T\"\"2T3U"),
          peg$decode("8!7b+D$ #7C,#&7C\"+2%7c+(%4#6W#!!%$## \"$\"# \"\"# \"9*\" 3V"),
          peg$decode("!!87c*) \"7A*# \"7\x829*$$\"\" 2\"# \"+1$7:+'%4\"6X\" %$\"# \"\"# \"*C \"!7A+2$7J+(%4\"6Y\"! %$\"# \"\"# \"*# \"7I"),
          peg$decode(".Z\"\"2Z3["),
          peg$decode(".\\\"\"2\\3]"),
          peg$decode("8!7D+D$ #7G,#&7G\"+2%7D+(%4#6_#!!%$## \"$\"# \"\"# \"*O \"!7E+D$ #7H,#&7H\"+2%7E+(%4#6_#!!%$## \"$\"# \"\"# \"9*\" 3^"),
          peg$decode("!!87D*) \"7A*# \"7\x829*$$\"\" 2\"# \"+1$7:+'%4\"6X\" %$\"# \"\"# \"*C \"!7A+2$7J+(%4\"6Y\"! %$\"# \"\"# \"*# \"7I"),
          peg$decode("!!87E*) \"7A*# \"7\x829*$$\"\" 2\"# \"+1$7:+'%4\"6X\" %$\"# \"\"# \"*C \"!7A+2$7J+(%4\"6Y\"! %$\"# \"\"# \"*# \"7I"),
          peg$decode("!7A+1$7\x83+'%4\"6`\" %$\"# \"\"# \""),
          peg$decode("7K*\\ \"!.<\"\"2<3=+?$!8719*$$\"\" 2\"# \"+'%4\"6a\" %$\"# \"\"# \"*) \"7O*# \"7P"),
          peg$decode("7L*# \"7M"),
          peg$decode("7E*\xB3 \"7D*\xAD \"7A*\xA7 \"!.b\"\"2b3c+& 4!6d! %*\x90 \"!.e\"\"2e3f+& 4!6g! %*y \"!.h\"\"2h3i+& 4!6j! %*b \"!.k\"\"2k3l+& 4!6m! %*K \"!.n\"\"2n3o+& 4!6p! %*4 \"!.q\"\"2q3r+& 4!6s! %"),
          peg$decode("!!87N*# \"7\x829*$$\"\" 2\"# \"+1$7:+'%4\"6X\" %$\"# \"\"# \""),
          peg$decode("7L*; \"71*5 \".t\"\"2t3u*) \".v\"\"2v3w"),
          peg$decode("!.t\"\"2t3u+M$!!78+-$78+#%'\"%$\"# \"\"# \"+! (%+(%4\"6x\"! %$\"# \"\"# \""),
          peg$decode("!.v\"\"2v3w+a$!!78+A$78+7%78+-%78+#%'$%$$# \"$## \"$\"# \"\"# \"+! (%+(%4\"6x\"! %$\"# \"\"# \""),
          peg$decode("87S*# \"7R9*\" 3y"),
          peg$decode("!7p+{$ #!!87\x829*$$\"\" 2\"# \"+-$7:+#%'\"%$\"# \"\"# \",F&!!87\x829*$$\"\" 2\"# \"+-$7:+#%'\"%$\"# \"\"# \"\"+#%'\"%$\"# \"\"# \""),
          peg$decode("!7q+\x85$ #!!87r9*$$\"\" 2\"# \"+-$7:+#%'\"%$\"# \"\"# \",F&!!87r9*$$\"\" 2\"# \"+-$7:+#%'\"%$\"# \"\"# \"\"+-%7r+#%'#%$## \"$\"# \"\"# \""),
          peg$decode("!7q+\x91$ #!!87r*# \"7\x829*$$\"\" 2\"# \"+-$7:+#%'\"%$\"# \"\"# \",L&!!87r*# \"7\x829*$$\"\" 2\"# \"+-$7:+#%'\"%$\"# \"\"# \"\"+-%7r+#%'#%$## \"$\"# \"\"# \""),
          peg$decode(".z\"\"2z3{"),
          peg$decode(".|\"\"2|3}"),
          peg$decode(".~\"\"2~3"),
          peg$decode(".\x80\"\"2\x803\x81"),
          peg$decode(".\x82\"\"2\x823\x83"),
          peg$decode(".\x84\"\"2\x843\x85"),
          peg$decode(".\x86\"\"2\x863\x87"),
          peg$decode(".\x88\"\"2\x883\x89"),
          peg$decode(".\x8A\"\"2\x8A3\x8B"),
          peg$decode(".\x8C\"\"2\x8C3\x8D"),
          peg$decode(".\x8E\"\"2\x8E3\x8F"),
          peg$decode(".\x90\"\"2\x903\x91"),
          peg$decode(".\x92\"\"2\x923\x93"),
          peg$decode(".\x94\"\"2\x943\x95"),
          peg$decode(".\x96\"\"2\x963\x97"),
          peg$decode(".\x98\"\"2\x983\x99"),
          peg$decode(".\x9A\"\"2\x9A3\x9B"),
          peg$decode(".\x9C\"\"2\x9C3\x9D"),
          peg$decode(".\x9E\"\"2\x9E3\x9F"),
          peg$decode(".\xA0\"\"2\xA03\xA1"),
          peg$decode(".\xA2\"\"2\xA23\xA3"),
          peg$decode(".\xA4\"\"2\xA43\xA5"),
          peg$decode(".\xA6\"\"2\xA63\xA7"),
          peg$decode(".\xA8\"\"2\xA83\xA9"),
          peg$decode(".\x88\"\"2\x883\x89"),
          peg$decode(".\xAA\"\"2\xAA3\xAB"),
          peg$decode(" #0\xAC\"\"1!3\xAD,)&0\xAC\"\"1!3\xAD\""),
          peg$decode(".\xAE\"\"2\xAE3\xAF*# \"7Y"),
          peg$decode(".\xB0\"\"2\xB03\xB1"),
          peg$decode(".\xB2\"\"2\xB23\xB3"),
          peg$decode("! #-\"\"1!3K,(&-\"\"1!3K\"+A$!8.\xB2\"\"2\xB23\xB39+$$\"# 2\"\" \"+#%'\"%$\"# \"\"# \""),
          peg$decode(" \xB4"),
          peg$decode("!7\xA3+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u03A3 \"!7\xA5+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u037A \"!7\xAA+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u0351 \"!7\xAB+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u0328 \"!7\xAE+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u02FF \"!7\xAF+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u02D6 \"!7\xC3+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u02AD \"!7\xC4+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u0284 \"!7\xC5+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u025B \"!7\xC8+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u0232 \"!7\xCE+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u0209 \"!7\xD2+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u01E0 \"!7\xD6+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u01B7 \"!7\xE1+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u018E \"!7\xE2+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u0165 \"!7\xE6+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u013C \"!7\xEC+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\u0113 \"!7\xED+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\xEA \"!7\xF3+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\xC1 \"!7\u010C+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*\x98 \"!7\u010D+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*o \"!7\u0119+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"*F \"!7\u011A+;$!87<9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \""),
          peg$decode("8!7\xEE+& 4!6\xB6! %9*\" 3\xB5"),
          peg$decode("8!7\u0110+& 4!6\xB8! %*. \"!7\xCB+& 4!6\xB9! %9*\" 3\xB7"),
          peg$decode("87u*) \"7v*# \"7w9*\" 3\xBA"),
          peg$decode("7[*# \"7Z"),
          peg$decode("!7\x94+\x8D$ #!7\x84+A$7y+7%7\x84+-%7\x94+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x84+A$7y+7%7\x84+-%7\x94+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6\xBB\"\"! %$\"# \"\"# \""),
          peg$decode("8.\xBD\"\"2\xBD3\xBE*) \".\xBF\"\"2\xBF3\xC09*\" 3\xBC"),
          peg$decode("!7z+\x8D$ #!7\x84+A$7{+7%7\x84+-%7z+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x84+A$7{+7%7\x84+-%7z+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6\xBB\"\"! %$\"# \"\"# \""),
          peg$decode("87g*\x81 \"7h*{ \"!!7e+;$!87e9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"+! (%*L \"!!7f+;$!87f9*$$\"\" 2\"# \"+#%'\"%$\"# \"\"# \"+! (%9*\" 3\xC1"),
          peg$decode("!7|+\x8D$ #!7\x84+A$7}+7%7\x84+-%7|+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x84+A$7}+7%7\x84+-%7|+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \"*# \"7\x8C"),
          peg$decode("!7~+\x8D$ #!7\x84+A$7\x80+7%7\x84+-%7~+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x84+A$7\x80+7%7\x84+-%7~+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \""),
          peg$decode("87k*/ \"7j*) \"7i*# \"7l9*\" 3\xC2"),
          peg$decode("8.\xC4\"\"2\xC43\xC5*Y \".\xC6\"\"2\xC63\xC7*M \".\xC8\"\"2\xC83\xC9*A \".\xCA\"\"2\xCA3\xCB*5 \".\xCC\"\"2\xCC3\xCD*) \".\xCE\"\"2\xCE3\xCF9*\" 3\xC3"),
          peg$decode("80\xD1\"\"1!3\xD29*\" 3\xD0"),
          peg$decode("8.\xAA\"\"2\xAA3\xAB*M \".\xD4\"\"2\xD43\xD5*A \".\xD6\"\"2\xD63\xD7*5 \".\xD8\"\"2\xD83\xD9*) \".\xDA\"\"2\xDA3\xDB9*\" 3\xD3"),
          peg$decode(" #7\x81*) \"7\x83*# \"7Q,/&7\x81*) \"7\x83*# \"7Q\""),
          peg$decode(" #7\x81*# \"7T,)&7\x81*# \"7T\""),
          peg$decode("87\xE2*# \"7\xED9*\" 3\xDC"),
          peg$decode("!7\x90+=$7\x84+3%7\x86+)%4#6\xDD#\"\" %$## \"$\"# \"\"# \""),
          peg$decode("!7\x90+R$7\x84+H%7\xE1+>%7\x84+4%7\x93+*%4%6\xDE%#$\" %$%# \"$$# \"$## \"$\"# \"\"# \""),
          peg$decode("!7\x90+R$7\x84+H%7\xD6+>%7\x84+4%7)+*%4%6\xDF%#$\" %$%# \"$$# \"$## \"$\"# \"\"# \"*\xCD \"!7\x90+\xC2$7\x84+\xB8%7\xD6+\xAE%7\x84+\xA4%7`+\x9A% #!7\x90+7$7V+-%7\x84+#%'#%$## \"$\"# \"\"# \"+E$,B&!7\x90+7$7V+-%7\x84+#%'#%$## \"$\"# \"\"# \"\"\"\" \"*# \" $+=%7\x84+3%7a+)%4(6\xE0(\"'%%$(# \"$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \""),
          peg$decode("!7\x90+z$7\x84+p%7\xAB+f%7\x84+\\%7\x90+R%7\x84+H%7\xA3+>%7\x84+4%7\x90+*%4)6\xE1)#($ %$)# \"$(# \"$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \""),
          peg$decode("87\xE6*# \"7\xD49*\" 3\xE2"),
          peg$decode("8!7\x90+q$7\x84+g%7\x8B+]%7\x84+S%7\x90+I%7\x84+?%7\xC5+5%7F++%4(6\xE3($'%# %$(# \"$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \"*] \"!7\x90+R$7\x84+H%7\x8B+>%7\x84+4%7\x90+*%4%6\xE4%#$\" %$%# \"$$# \"$## \"$\"# \"\"# \"9*\" 3\xE2"),
          peg$decode("7\xFC*B \"!7\u0107+7$7\x84+-%7\u010D+#%'#%$## \"$\"# \"\"# \""),
          peg$decode("8!7\x90+R$7\x84+H%7\x8D+>%7\x84+4%7\x90+*%4%6\xE6%#$\" %$%# \"$$# \"$## \"$\"# \"\"# \"9*\" 3\xE5"),
          peg$decode("8!7\xEC+=$7\x84+3%7\x91+)%4#6\xE8#\"\" %$## \"$\"# \"\"# \"9*\" 3\xE7"),
          peg$decode("!70+\xBF$ #!7\x84+Z$7b+P%7\x84+F%7)+<%7\x84+2%7c+(%4&6\xE9&!\"%$&# \"$%# \"$$# \"$## \"$\"# \"\"# \",e&!7\x84+Z$7b+P%7\x84+F%7)+<%7\x84+2%7c+(%4&6\xE9&!\"%$&# \"$%# \"$$# \"$## \"$\"# \"\"# \"\"+)%4\"6\xEA\"\"! %$\"# \"\"# \""),
          peg$decode("7\x8F*G \"7\x8C*A \"7\x8E*; \"7\x8A*5 \"7\x89*/ \"7\x87*) \"7\x88*# \"7\x90"),
          peg$decode("87Z*) \"7[*# \"7_9*\" 3\xEB"),
          peg$decode("!7\x92+=$7\x84+3%7\x91+)%4#6\xEC#\"\" %$## \"$\"# \"\"# \"*# \"7\x91"),
          peg$decode("!7\x93+\x8D$ #!7\x84+A$7\x95+7%7\x84+-%7\x93+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x84+A$7\x95+7%7\x84+-%7\x93+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6\xBB\"\"! %$\"# \"\"# \""),
          peg$decode("87\\*) \"7]*# \"7^9*\" 3\xED"),
          peg$decode("! #0\xEE\"\"1!3\xEF+,$,)&0\xEE\"\"1!3\xEF\"\"\" \"+' 4!6\xF0!! %"),
          peg$decode("!!!7>+7$7W+-%7\x96+#%'#%$## \"$\"# \"\"# \"+' 4!6\xF1!! %*/ \"!7\x96+' 4!6\xF2!! %+' 4!6\xF3!! %"),
          peg$decode("!.\xF4\"\"2\xF43\xF5+-$7>+#%'\"%$\"# \"\"# \""),
          peg$decode(".\xF6\"\"2\xF63\xF7"),
          peg$decode(".\xF6\"\"2\xF63\xF7"),
          peg$decode(".\xF6\"\"2\xF63\xF7"),
          peg$decode("/\xF8\"\"1%3\xF9"),
          peg$decode("/\xFA\"\"1&3\xFB"),
          peg$decode("/\xFC\"\"1#3\xFD"),
          peg$decode("/\xFE\"\"1%3\xFF"),
          peg$decode("/\u0100\"\"1#3\u0101"),
          peg$decode("/\u0102\"\"1%3\u0103"),
          peg$decode("/\u0104\"\"1'3\u0105"),
          peg$decode("/\u0106\"\"1#3\u0107"),
          peg$decode("/\u0108\"\"1%3\u0109"),
          peg$decode("/\u010A\"\"1\"3\u010B"),
          peg$decode("/\u010C\"\"1#3\u010D"),
          peg$decode("/\u010E\"\"1&3\u010F"),
          peg$decode("/\u0110\"\"1-3\u0111"),
          peg$decode("/\u0112\"\"1&3\u0113"),
          peg$decode("/\u0114\"\"1%3\u0115"),
          peg$decode("/\u0116\"\"1'3\u0117"),
          peg$decode("/\u0118\"\"1\"3\u0119"),
          peg$decode("/\u011A\"\"1'3\u011B"),
          peg$decode("/\u011C\"\"1$3\u011D"),
          peg$decode("/\u011E\"\"1$3\u011F"),
          peg$decode("/\u0120\"\"1%3\u0121"),
          peg$decode("/\u0122\"\"1'3\u0123"),
          peg$decode("/\u0124\"\"1&3\u0125"),
          peg$decode("/\u0126\"\"1&3\u0127"),
          peg$decode("/\u0128\"\"1(3\u0129"),
          peg$decode("/\u012A\"\"1*3\u012B"),
          peg$decode("!7\x84+3$/\u012C\"\"1&3\u012D+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u012E\"\"1%3\u012F"),
          peg$decode("/\u0130\"\"1(3\u0131"),
          peg$decode("/\u0132\"\"1'3\u0133"),
          peg$decode("/\u0134\"\"1*3\u0135"),
          peg$decode("/\u0136\"\"1(3\u0137"),
          peg$decode("!7\x84+3$/\u0138\"\"1&3\u0139+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u013A\"\"1$3\u013B"),
          peg$decode("/\u013C\"\"1&3\u013D"),
          peg$decode("/\u013E\"\"1(3\u013F"),
          peg$decode("/\u0140\"\"1$3\u0141"),
          peg$decode("/@\"\"1!3\u0142"),
          peg$decode("/\u0143\"\"1$3\u0144"),
          peg$decode("/\u0145\"\"1$3\u0146"),
          peg$decode("/\u0147\"\"1#3\u0148"),
          peg$decode("/\u0149\"\"1&3\u014A"),
          peg$decode("/\u014B\"\"1&3\u014C"),
          peg$decode("/\u014D\"\"1)3\u014E"),
          peg$decode("/\u014F\"\"1&3\u0150"),
          peg$decode("!7\x84+3$/\u0151\"\"1'3\u0152+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u0153\"\"1$3\u0154"),
          peg$decode("/\u0155\"\"1%3\u0156"),
          peg$decode("/\u0157\"\"1#3\u0158"),
          peg$decode("/\u0159\"\"1'3\u015A"),
          peg$decode("/\u015B\"\"1$3\u015C"),
          peg$decode("/\u015D\"\"1$3\u015E"),
          peg$decode("/\u015F\"\"1%3\u0160"),
          peg$decode("/\u0161\"\"1&3\u0162"),
          peg$decode("/\u0163\"\"1\"3\u0164"),
          peg$decode("/\u0165\"\"1&3\u0166"),
          peg$decode("/\u0167\"\"1%3\u0168"),
          peg$decode("/\u0169\"\"1)3\u016A"),
          peg$decode("/\u016B\"\"1\"3\u016C"),
          peg$decode("/\u016D\"\"1%3\u016E"),
          peg$decode("/\u016F\"\"1'3\u0170"),
          peg$decode("/\u0171\"\"1(3\u0172"),
          peg$decode("/\u0173\"\"1)3\u0174"),
          peg$decode("/\u0175\"\"1%3\u0176"),
          peg$decode("!7\x84+3$/\u0177\"\"1&3\u0178+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u0179\"\"1'3\u017A"),
          peg$decode("/\u017B\"\"1'3\u017C"),
          peg$decode("/\u017D\"\"1)3\u017E"),
          peg$decode("/\u017F\"\"1$3\u0180"),
          peg$decode("/\u0181\"\"1\"3\u0182"),
          peg$decode("/\u0183\"\"1&3\u0184"),
          peg$decode("/\u0185\"\"1$3\u0186"),
          peg$decode("/\u0187\"\"1#3\u0188"),
          peg$decode("/\u0189\"\"1$3\u018A"),
          peg$decode("/\u018B\"\"1$3\u018C"),
          peg$decode("/\u018D\"\"1%3\u018E"),
          peg$decode("/\u018F\"\"1%3\u0190"),
          peg$decode("/\u0191\"\"1#3\u0192"),
          peg$decode("/\u0193\"\"1'3\u0194"),
          peg$decode("/\u0195\"\"1\"3\u0196"),
          peg$decode("/\u0197\"\"1#3\u0198"),
          peg$decode("/\u0199\"\"1'3\u019A"),
          peg$decode("/\u019B\"\"1$3\u019C"),
          peg$decode("/\u019D\"\"1&3\u019E"),
          peg$decode("/\u019F\"\"1\"3\u01A0"),
          peg$decode("/\u01A1\"\"1&3\u01A2"),
          peg$decode("/\u01A3\"\"1\"3\u01A4"),
          peg$decode("/\u01A5\"\"1\"3\u01A6"),
          peg$decode("/\u01A7\"\"1%3\u01A8"),
          peg$decode("/\u01A9\"\"1%3\u01AA"),
          peg$decode("/\u01AB\"\"1$3\u01AC"),
          peg$decode("/\u01AD\"\"1&3\u01AE"),
          peg$decode("/\u01AF\"\"1'3\u01B0"),
          peg$decode("/\u01B1\"\"1%3\u01B2"),
          peg$decode("/\u01B3\"\"1%3\u01B4"),
          peg$decode("/\u01B5\"\"1*3\u01B6"),
          peg$decode("/\u01B7\"\"1&3\u01B8"),
          peg$decode("/\u01B9\"\"1'3\u01BA"),
          peg$decode("/\u01BB\"\"1'3\u01BC"),
          peg$decode("/\u01BD\"\"1&3\u01BE"),
          peg$decode("!7\x84+3$/\u01BF\"\"1'3\u01C0+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u01C1\"\"1(3\u01C2"),
          peg$decode("/\u01C3\"\"1(3\u01C4"),
          peg$decode("/\u01C5\"\"1#3\u01C6"),
          peg$decode("/\u01C7\"\"1)3\u01C8"),
          peg$decode("!7\x84+3$/\u01C9\"\"1&3\u01CA+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u01CB\"\"1#3\u01CC"),
          peg$decode("/\u01CD\"\"1'3\u01CE"),
          peg$decode("/\u01CF\"\"1&3\u01D0"),
          peg$decode("/\u01D1\"\"1%3\u01D2"),
          peg$decode("/\u01D3\"\"1$3\u01D4"),
          peg$decode("/\u01D5\"\"1)3\u01D6"),
          peg$decode("/\u01D7\"\"1$3\u01D8"),
          peg$decode("/\u01D9\"\"1\"3\u01DA"),
          peg$decode("/\u01DB\"\"1+3\u01DC"),
          peg$decode("/\u01DD\"\"1'3\u01DE"),
          peg$decode("/\u01DF\"\"1$3\u01E0"),
          peg$decode("/\u01E1\"\"1%3\u01E2"),
          peg$decode("/\u01E3\"\"1&3\u01E4"),
          peg$decode("!7\x84+3$/\u01E5\"\"1&3\u01E6+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u01E7\"\"1%3\u01E8"),
          peg$decode("/\u01E9\"\"1&3\u01EA"),
          peg$decode("/\u01EB\"\"1&3\u01EC"),
          peg$decode("/\u01ED\"\"1$3\u01EE"),
          peg$decode("/\u01EF\"\"1'3\u01F0"),
          peg$decode("/\u01F1\"\"1$3\u01F2"),
          peg$decode("/\u01F3\"\"1%3\u01F4")
        ],

        peg$currPos          = 0,
        peg$reportedPos      = 0,
        peg$cachedPos        = 0,
        peg$cachedPosDetails = { line: 1, column: 1, seenCR: false },
        peg$maxFailPos       = 0,
        peg$maxFailExpected  = [],
        peg$silentFails      = 0,

        peg$cache = {},
        peg$result;

    if ("startRule" in options) {
      if (!(options.startRule in peg$startRuleIndices)) {
        throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
      }

      peg$startRuleIndex = peg$startRuleIndices[options.startRule];
    }

    function text() {
      return input.substring(peg$reportedPos, peg$currPos);
    }

    function offset() {
      return peg$reportedPos;
    }

    function line() {
      return peg$computePosDetails(peg$reportedPos).line;
    }

    function column() {
      return peg$computePosDetails(peg$reportedPos).column;
    }

    function expected(description) {
      throw peg$buildException(
        null,
        [{ type: "other", description: description }],
        peg$reportedPos
      );
    }

    function error(message) {
      throw peg$buildException(message, null, peg$reportedPos);
    }

    function peg$computePosDetails(pos) {
      function advance(details, startPos, endPos) {
        var p, ch;

        for (p = startPos; p < endPos; p++) {
          ch = input.charAt(p);
          if (ch === "\n") {
            if (!details.seenCR) { details.line++; }
            details.column = 1;
            details.seenCR = false;
          } else if (ch === "\r" || ch === "\u2028" || ch === "\u2029") {
            details.line++;
            details.column = 1;
            details.seenCR = true;
          } else {
            details.column++;
            details.seenCR = false;
          }
        }
      }

      if (peg$cachedPos !== pos) {
        if (peg$cachedPos > pos) {
          peg$cachedPos = 0;
          peg$cachedPosDetails = { line: 1, column: 1, seenCR: false };
        }
        advance(peg$cachedPosDetails, peg$cachedPos, pos);
        peg$cachedPos = pos;
      }

      return peg$cachedPosDetails;
    }

    function peg$fail(expected) {
      if (peg$currPos < peg$maxFailPos) { return; }

      if (peg$currPos > peg$maxFailPos) {
        peg$maxFailPos = peg$currPos;
        peg$maxFailExpected = [];
      }

      peg$maxFailExpected.push(expected);
    }

    function peg$buildException(message, expected, pos) {
      function cleanupExpected(expected) {
        var i = 1;

        expected.sort(function(a, b) {
          if (a.description < b.description) {
            return -1;
          } else if (a.description > b.description) {
            return 1;
          } else {
            return 0;
          }
        });

        while (i < expected.length) {
          if (expected[i - 1] === expected[i]) {
            expected.splice(i, 1);
          } else {
            i++;
          }
        }
      }

      function buildMessage(expected, found) {
        function stringEscape(s) {
          function hex(ch) { return ch.charCodeAt(0).toString(16).toUpperCase(); }

          return s
            .replace(/\\/g,   '\\\\')
            .replace(/"/g,    '\\"')
            .replace(/\x08/g, '\\b')
            .replace(/\t/g,   '\\t')
            .replace(/\n/g,   '\\n')
            .replace(/\f/g,   '\\f')
            .replace(/\r/g,   '\\r')
            .replace(/[\x00-\x07\x0B\x0E\x0F]/g, function(ch) { return '\\x0' + hex(ch); })
            .replace(/[\x10-\x1F\x80-\xFF]/g,    function(ch) { return '\\x'  + hex(ch); })
            .replace(/[\u0180-\u0FFF]/g,         function(ch) { return '\\u0' + hex(ch); })
            .replace(/[\u1080-\uFFFF]/g,         function(ch) { return '\\u'  + hex(ch); });
        }

        var expectedDescs = new Array(expected.length),
            expectedDesc, foundDesc, i;

        for (i = 0; i < expected.length; i++) {
          expectedDescs[i] = expected[i].description;
        }

        expectedDesc = expected.length > 1
          ? expectedDescs.slice(0, -1).join(", ")
              + " or "
              + expectedDescs[expected.length - 1]
          : expectedDescs[0];

        foundDesc = found ? "\"" + stringEscape(found) + "\"" : "end of input";

        return "Expected " + expectedDesc + " but " + foundDesc + " found.";
      }

      var posDetails = peg$computePosDetails(pos),
          found      = pos < input.length ? input.charAt(pos) : null;

      if (expected !== null) {
        cleanupExpected(expected);
      }

      return new SyntaxError(
        message !== null ? message : buildMessage(expected, found),
        expected,
        found,
        pos,
        posDetails.line,
        posDetails.column
      );
    }

    function peg$decode(s) {
      var bc = new Array(s.length), i;

      for (i = 0; i < s.length; i++) {
        bc[i] = s.charCodeAt(i) - 32;
      }

      return bc;
    }

    function peg$parseRule(index) {
      var bc    = peg$bytecode[index],
          ip    = 0,
          ips   = [],
          end   = bc.length,
          ends  = [],
          stack = [],
          params, i;

      var key    = peg$currPos * 251 + index,
          cached = peg$cache[key];

      if (cached) {
        peg$currPos = cached.nextPos;
        return cached.result;
      }

      function protect(object) {
        return Object.prototype.toString.apply(object) === "[object Array]" ? [] : object;
      }

      while (true) {
        while (ip < end) {
          switch (bc[ip]) {
            case 0:
              stack.push(protect(peg$consts[bc[ip + 1]]));
              ip += 2;
              break;

            case 1:
              stack.push(peg$currPos);
              ip++;
              break;

            case 2:
              stack.pop();
              ip++;
              break;

            case 3:
              peg$currPos = stack.pop();
              ip++;
              break;

            case 4:
              stack.length -= bc[ip + 1];
              ip += 2;
              break;

            case 5:
              stack.splice(-2, 1);
              ip++;
              break;

            case 6:
              stack[stack.length - 2].push(stack.pop());
              ip++;
              break;

            case 7:
              stack.push(stack.splice(stack.length - bc[ip + 1], bc[ip + 1]));
              ip += 2;
              break;

            case 8:
              stack.pop();
              stack.push(input.substring(stack[stack.length - 1], peg$currPos));
              ip++;
              break;

            case 9:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (stack[stack.length - 1]) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 10:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (stack[stack.length - 1] === peg$FAILED) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 11:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (stack[stack.length - 1] !== peg$FAILED) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 12:
              if (stack[stack.length - 1] !== peg$FAILED) {
                ends.push(end);
                ips.push(ip);

                end = ip + 2 + bc[ip + 1];
                ip += 2;
              } else {
                ip += 2 + bc[ip + 1];
              }

              break;

            case 13:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (input.length > peg$currPos) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 14:
              ends.push(end);
              ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

              if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length) === peg$consts[bc[ip + 1]]) {
                end = ip + 4 + bc[ip + 2];
                ip += 4;
              } else {
                end = ip + 4 + bc[ip + 2] + bc[ip + 3];
                ip += 4 + bc[ip + 2];
              }

              break;

            case 15:
              ends.push(end);
              ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

              if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length).toLowerCase() === peg$consts[bc[ip + 1]]) {
                end = ip + 4 + bc[ip + 2];
                ip += 4;
              } else {
                end = ip + 4 + bc[ip + 2] + bc[ip + 3];
                ip += 4 + bc[ip + 2];
              }

              break;

            case 16:
              ends.push(end);
              ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

              if (peg$consts[bc[ip + 1]].test(input.charAt(peg$currPos))) {
                end = ip + 4 + bc[ip + 2];
                ip += 4;
              } else {
                end = ip + 4 + bc[ip + 2] + bc[ip + 3];
                ip += 4 + bc[ip + 2];
              }

              break;

            case 17:
              stack.push(input.substr(peg$currPos, bc[ip + 1]));
              peg$currPos += bc[ip + 1];
              ip += 2;
              break;

            case 18:
              stack.push(peg$consts[bc[ip + 1]]);
              peg$currPos += peg$consts[bc[ip + 1]].length;
              ip += 2;
              break;

            case 19:
              stack.push(peg$FAILED);
              if (peg$silentFails === 0) {
                peg$fail(peg$consts[bc[ip + 1]]);
              }
              ip += 2;
              break;

            case 20:
              peg$reportedPos = stack[stack.length - 1 - bc[ip + 1]];
              ip += 2;
              break;

            case 21:
              peg$reportedPos = peg$currPos;
              ip++;
              break;

            case 22:
              params = bc.slice(ip + 4, ip + 4 + bc[ip + 3]);
              for (i = 0; i < bc[ip + 3]; i++) {
                params[i] = stack[stack.length - 1 - params[i]];
              }

              stack.splice(
                stack.length - bc[ip + 2],
                bc[ip + 2],
                peg$consts[bc[ip + 1]].apply(null, params)
              );

              ip += 4 + bc[ip + 3];
              break;

            case 23:
              stack.push(peg$parseRule(bc[ip + 1]));
              ip += 2;
              break;

            case 24:
              peg$silentFails++;
              ip++;
              break;

            case 25:
              peg$silentFails--;
              ip++;
              break;

            default:
              throw new Error("Invalid opcode: " + bc[ip] + ".");
          }
        }

        if (ends.length > 0) {
          end = ends.pop();
          ip = ips.pop();
        } else {
          break;
        }
      }

      peg$cache[key] = { nextPos: peg$currPos, result: stack[0] };

      return stack[0];
    }


      //var unroll = options.util.makeUnroll(line, column, offset, SyntaxError)
      //var ast    = options.util.makeAST(line, column, offset, options)

      // Header/utility functions for grammar match bodies.
      //

      function extractList(list, index) {
        var result = new Array(list.length), i;

        for (i = 0; i < list.length; i++) {
          result[i] = list[i][index];
        }

        return result;
      }

      function buildList(first, rest, index) {
        return [first].concat(extractList(rest, index));
      }

      function buildTree(first, rest, builder) {
        var result = first, i;

        for (i = 0; i < rest.length; i++) {
          result = builder(result, rest[i]);
        }

        return result;
      }

      function buildBinaryPredicate(first, rest) {
        return buildTree(first, rest, function(result, element) {
          return {
            type:     "BinaryPredicate",
            operator: element[1],
            left:     result,
            right:    element[3]
          };
        });
      }

      function buildBinaryExpression(first, rest) {
        return buildTree(first, rest, function(result, element) {
          return {
            type:     "BinaryExpression",
            operator: element[1],
            left:     result,
            right:    element[3]
          };
        });
      }

      function optionalList(value) {
        return value !== null ? value : [];
      }


    peg$result = peg$parseRule(peg$startRuleIndex);

    if (peg$result !== peg$FAILED && peg$currPos === input.length) {
      return peg$result;
    } else {
      if (peg$result !== peg$FAILED && peg$currPos < input.length) {
        peg$fail({ type: "end", description: "end of input" });
      }

      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
    }
  }

  return {
    SyntaxError: SyntaxError,
    parse:       parse
  };
})();