module.exports = (function() {
  /*
   * Generated by PEG.js 0.8.0.
   *
   * http://pegjs.majda.cz/
   */

  function peg$subclass(child, parent) {
    function ctor() { this.constructor = child; }
    ctor.prototype = parent.prototype;
    child.prototype = new ctor();
  }

  function SyntaxError(message, expected, found, offset, line, column) {
    this.message  = message;
    this.expected = expected;
    this.found    = found;
    this.offset   = offset;
    this.line     = line;
    this.column   = column;

    this.name     = "SyntaxError";
  }

  peg$subclass(SyntaxError, Error);

  function parse(input) {
    var options = arguments.length > 1 ? arguments[1] : {},

        peg$FAILED = {},

        peg$startRuleIndices = { start: 0 },
        peg$startRuleIndex   = 0,

        peg$consts = [
          { type: "other", description: "type name" },
          { type: "other", description: "type" },
          peg$FAILED,
          [],
          null,
          { type: "other", description: "cast" },
          function(value, type_name) {
              return {
                type: 'CastExpression',
                value: value,
                type_name: type_name
              };
            },
          function(operator, argument) {
                return {
                  type: 'UnaryExpression',
                  operator: operator,
                  argument: argument,
                  fixity: 'prefix'
                };
              },
          function(first, rest) { return buildBinaryExpression(first, rest); },
          { type: "other", description: "limit" },
          function(limit) { return { type: 'Limit', value: limit } },
          { type: "other", description: "WHERE clause" },
          { type: "other", description: "now" },
          { type: "other", description: "literal" },
          function(element) {
                  return optionalList(element);
                },
          function(first, rest) { return Array.prototype.concat.apply(first, rest); },
          function() {
                return {
                  type: 'ListExpression',
                  elements: []
                }
              },
          function(elements) {
                return {
                  type: 'ListExpression',
                  elements: elements
                }
              },
          { type: "other", description: "function call" },
          function(callee) {
              return {
                type: 'FunctionCall',
                callee: callee,
                arguments: []
              };
            },
          function(callee, elements) {
              return {
                type: 'FunctionCall',
                callee: callee,
                arguments: elements
              };
            },
          function(expression) { return expression; },
          /^[0-9]/,
          { type: "class", value: "[0-9]", description: "[0-9]" },
          /^[1-9]/,
          { type: "class", value: "[1-9]", description: "[1-9]" },
          "0",
          { type: "literal", value: "0", description: "\"0\"" },
          function() {
              return { type: "Literal", dataType: 'integer', value: 0 };
            },
          function() {
              return { type: "Literal", dataType: 'integer', value: parseInt(text()) };
            },
          "e",
          { type: "literal", value: "e", description: "\"e\"" },
          /^[+\-]/,
          { type: "class", value: "[+\\-]", description: "[+\\-]" },
          function() {
                return { type: "Literal", dataType: 'float', value: parseFloat(text()) };
              },
          function() {
                return { type: "Literal", dataType: 'integer', value: parseFloat(text()) };
              },
          /^[0-9a-f]/i,
          { type: "class", value: "[0-9a-f]i", description: "[0-9a-f]i" },
          "0x",
          { type: "literal", value: "0x", description: "\"0x\"" },
          function(digits) {
                return { type: "Literal", dataType: 'integer', value: parseInt(digits, 16) };
               },
          { type: "any", description: "any character" },
          /^[A-Za-z_]/,
          { type: "class", value: "[A-Za-z_]", description: "[A-Za-z_]" },
          { type: "other", description: "identifier" },
          function(first, rest) {
                return {
                  type: "Identifier",
                  name: first + rest.join("")
                };
              },
          void 0,
          function(name) { return name; },
          { type: "other", description: "number" },
          function(literal) {
                return literal;
              },
          { type: "other", description: "numeric constant" },
          "\\",
          { type: "literal", value: "\\", description: "\"\\\\\"" },
          { type: "other", description: "identifier with brackets" },
          function(chars) {
                return {
                  type: "Identifier",
                  name: chars.join("")
                };
              },
          function() { return text(); },
          function(sequence) { return sequence; },
          "\"",
          { type: "literal", value: "\"", description: "\"\\\"\"" },
          "'",
          { type: "literal", value: "'", description: "\"'\"" },
          { type: "other", description: "string" },
          function(chars) {
                return { type: "Literal", dataType: 'string', value: chars.join("") };
              },
          function() { return ""; },
          function() { return "\0"; },
          "b",
          { type: "literal", value: "b", description: "\"b\"" },
          function() { return "\b";   },
          "f",
          { type: "literal", value: "f", description: "\"f\"" },
          function() { return "\f";   },
          "n",
          { type: "literal", value: "n", description: "\"n\"" },
          function() { return "\n";   },
          "r",
          { type: "literal", value: "r", description: "\"r\"" },
          function() { return "\r";   },
          "t",
          { type: "literal", value: "t", description: "\"t\"" },
          function() { return "\t";   },
          "v",
          { type: "literal", value: "v", description: "\"v\"" },
          function() { return "\x0B"; },
          "x",
          { type: "literal", value: "x", description: "\"x\"" },
          "u",
          { type: "literal", value: "u", description: "\"u\"" },
          function(digits) {
                return String.fromCharCode(parseInt(digits, 16));
              },
          { type: "other", description: "comment" },
          ".",
          { type: "literal", value: ".", description: "\".\"" },
          ",",
          { type: "literal", value: ",", description: "\",\"" },
          ":",
          { type: "literal", value: ":", description: "\":\"" },
          ";",
          { type: "literal", value: ";", description: "\";\"" },
          "--",
          { type: "literal", value: "--", description: "\"--\"" },
          "-",
          { type: "literal", value: "-", description: "\"-\"" },
          "+",
          { type: "literal", value: "+", description: "\"+\"" },
          "*",
          { type: "literal", value: "*", description: "\"*\"" },
          "/",
          { type: "literal", value: "/", description: "\"/\"" },
          "%",
          { type: "literal", value: "%", description: "\"%\"" },
          "~",
          { type: "literal", value: "~", description: "\"~\"" },
          "(",
          { type: "literal", value: "(", description: "\"(\"" },
          ")",
          { type: "literal", value: ")", description: "\")\"" },
          "[",
          { type: "literal", value: "[", description: "\"[\"" },
          "]",
          { type: "literal", value: "]", description: "\"]\"" },
          "||",
          { type: "literal", value: "||", description: "\"||\"" },
          "<",
          { type: "literal", value: "<", description: "\"<\"" },
          ">",
          { type: "literal", value: ">", description: "\">\"" },
          "<=",
          { type: "literal", value: "<=", description: "\"<=\"" },
          ">=",
          { type: "literal", value: ">=", description: "\">=\"" },
          "=",
          { type: "literal", value: "=", description: "\"=\"" },
          "==",
          { type: "literal", value: "==", description: "\"==\"" },
          "!=",
          { type: "literal", value: "!=", description: "\"!=\"" },
          "<>",
          { type: "literal", value: "<>", description: "\"<>\"" },
          "\n",
          { type: "literal", value: "\n", description: "\"\\n\"" },
          /^[^\n]/,
          { type: "class", value: "[^\\n]", description: "[^\\n]" },
          "//",
          { type: "literal", value: "//", description: "\"//\"" },
          "/*",
          { type: "literal", value: "/*", description: "\"/*\"" },
          "*/",
          { type: "literal", value: "*/", description: "\"*/\"" },
          "",
          { type: "other", description: "null" },
          function() { return { type: "Literal", dataType: 'null', value: null }; },
          { type: "other", description: "boolean" },
          function() { return { type: "Literal", dataType: 'boolean', value: true  }; },
          function() { return { type: "Literal", dataType: 'boolean', value: false }; },
          { type: "other", description: "reserved word" },
          { type: "other", description: "shift operator" },
          "<<",
          { type: "literal", value: "<<", description: "\"<<\"" },
          ">>",
          { type: "literal", value: ">>", description: "\">>\"" },
          { type: "other", description: "comparison" },
          { type: "other", description: "equality operator" },
          { type: "other", description: "whitespace" },
          "\t",
          { type: "literal", value: "\t", description: "\"\\t\"" },
          "\x0B",
          { type: "literal", value: "\x0B", description: "\"\\x0B\"" },
          "\f",
          { type: "literal", value: "\f", description: "\"\\f\"" },
          " ",
          { type: "literal", value: " ", description: "\" \"" },
          "\xA0",
          { type: "literal", value: "\xA0", description: "\"\\xA0\"" },
          "\uFEFF",
          { type: "literal", value: "\uFEFF", description: "\"\\uFEFF\"" },
          { type: "other", description: "line terminator" },
          /^[\n\r\u2028\u2029]/,
          { type: "class", value: "[\\n\\r\\u2028\\u2029]", description: "[\\n\\r\\u2028\\u2029]" },
          { type: "other", description: "end of line" },
          "\r\n",
          { type: "literal", value: "\r\n", description: "\"\\r\\n\"" },
          "\r",
          { type: "literal", value: "\r", description: "\"\\r\"" },
          "\u2028",
          { type: "literal", value: "\u2028", description: "\"\\u2028\"" },
          "\u2029",
          { type: "literal", value: "\u2029", description: "\"\\u2029\"" },
          { type: "other", description: "postfix keyword" },
          function(argument, operator) {
                return {
                  type: 'UnaryExpression',
                  operator: operator,
                  argument: argument,
                  fixity: 'postfix'
                };
              },
          function(left, operator, right) {
                return {
                  type: 'LogicalExpression',
                  operator: operator,
                  left: left,
                  right: right
                };
              },
          function(left, operator, right) { return {
                   type: 'LogicalExpression',
                   operator: operator,
                   left: left,
                   right: right
                };
              },
          function(left, operator) { return buildBinaryExpression(first, rest); },
          function(value, low, high) {
                // TODO: use negated
                return {
                    type: 'BetweenPredicate',
                    value: value,
                    start: low,
                    stop:  high
                };
              },
          { type: "other", description: "text comparison" },
          function(value, operator, like, escapeChar) { return {
                  type: 'LikePredicate',
                  operator: operator,
                  left: value,
                  right: like,
                  escapeChar: escapeChar
                };
              },
          function(value, operator, like) { return {
                  type: 'LikePredicate',
                  operator: operator,
                  left: value,
                  right: like
                };
              },
          { type: "other", description: "regex expression" },
          function(value, operator, matcher) {
                return {
                  type: 'RegexPredicate',
                  operator: operator,
                  left: value,
                  right: matcher
                };
              },
          { type: "other", description: "not" },
          function(operator, argument) {
                return {
                  type: 'NotExpression',
                  operator: operator,
                  value: argument
                };
              },
          function(property) { return { name: property }; },
          function(first, rest) {
                return buildTree(first, rest, function(result, element) {
                  return {
                    type:     'MemberAccess',
                    object:   result,
                    name:     element.name
                  };
                });
              },
          { type: "other", description: "prefix operator" },
          function(operator, argument) {
              return {
                type: 'UnaryExpression',
                operator: operator,
                argument: argument,
                fixity: 'prefix'
              };
            },
          { type: "other", description: "multiplicative operator" },
          /^[A-Za-z0-9_:]/,
          { type: "class", value: "[A-Za-z0-9_:]", description: "[A-Za-z0-9_:]" },
          function(str) { return str.join(''); },
          function(c) { return { column: c[2], graph_namespace: c[1] }; },
          function(c) { return { column: c }; },
          function(gcn) { return gcn[1]; },
          "?",
          { type: "literal", value: "?", description: "\"?\"" },
          "now",
          { type: "literal", value: "now", description: "\"now\"" },
          "abort",
          { type: "literal", value: "ABORT", description: "\"ABORT\"" },
          "action",
          { type: "literal", value: "ACTION", description: "\"ACTION\"" },
          "add",
          { type: "literal", value: "ADD", description: "\"ADD\"" },
          "after",
          { type: "literal", value: "AFTER", description: "\"AFTER\"" },
          "all",
          { type: "literal", value: "ALL", description: "\"ALL\"" },
          "alter",
          { type: "literal", value: "ALTER", description: "\"ALTER\"" },
          "analyze",
          { type: "literal", value: "ANALYZE", description: "\"ANALYZE\"" },
          "and",
          { type: "literal", value: "AND", description: "\"AND\"" },
          "array",
          { type: "literal", value: "ARRAY", description: "\"ARRAY\"" },
          "as",
          { type: "literal", value: "AS", description: "\"AS\"" },
          "asc",
          { type: "literal", value: "ASC", description: "\"ASC\"" },
          "attach",
          { type: "literal", value: "ATTACH", description: "\"ATTACH\"" },
          "autoincrement",
          { type: "literal", value: "AUTOINCREMENT", description: "\"AUTOINCREMENT\"" },
          "before",
          { type: "literal", value: "BEFORE", description: "\"BEFORE\"" },
          "begin",
          { type: "literal", value: "BEGIN", description: "\"BEGIN\"" },
          "between",
          { type: "literal", value: "BETWEEN", description: "\"BETWEEN\"" },
          "by",
          { type: "literal", value: "BY", description: "\"BY\"" },
          "cascade",
          { type: "literal", value: "CASCADE", description: "\"CASCADE\"" },
          "case",
          { type: "literal", value: "CASE", description: "\"CASE\"" },
          "cast",
          { type: "literal", value: "CAST", description: "\"CAST\"" },
          "check",
          { type: "literal", value: "CHECK", description: "\"CHECK\"" },
          "collate",
          { type: "literal", value: "COLLATE", description: "\"COLLATE\"" },
          "column",
          { type: "literal", value: "COLUMN", description: "\"COLUMN\"" },
          "commit",
          { type: "literal", value: "COMMIT", description: "\"COMMIT\"" },
          "conflict",
          { type: "literal", value: "CONFLICT", description: "\"CONFLICT\"" },
          "constraint",
          { type: "literal", value: "CONSTRAINT", description: "\"CONSTRAINT\"" },
          "create",
          { type: "literal", value: "CREATE", description: "\"CREATE\"" },
          "cross",
          { type: "literal", value: "CROSS", description: "\"CROSS\"" },
          "database",
          { type: "literal", value: "DATABASE", description: "\"DATABASE\"" },
          "default",
          { type: "literal", value: "DEFAULT", description: "\"DEFAULT\"" },
          "deferrable",
          { type: "literal", value: "DEFERRABLE", description: "\"DEFERRABLE\"" },
          "deferred",
          { type: "literal", value: "DEFERRED", description: "\"DEFERRED\"" },
          "delete",
          { type: "literal", value: "DELETE", description: "\"DELETE\"" },
          "desc",
          { type: "literal", value: "DESC", description: "\"DESC\"" },
          "detach",
          { type: "literal", value: "DETACH", description: "\"DETACH\"" },
          "distinct",
          { type: "literal", value: "DISTINCT", description: "\"DISTINCT\"" },
          "drop",
          { type: "literal", value: "DROP", description: "\"DROP\"" },
          { type: "literal", value: "E", description: "\"E\"" },
          "each",
          { type: "literal", value: "EACH", description: "\"EACH\"" },
          "else",
          { type: "literal", value: "ELSE", description: "\"ELSE\"" },
          "end",
          { type: "literal", value: "END", description: "\"END\"" },
          "escape",
          { type: "literal", value: "ESCAPE", description: "\"ESCAPE\"" },
          "except",
          { type: "literal", value: "EXCEPT", description: "\"EXCEPT\"" },
          "exclusive",
          { type: "literal", value: "EXCLUSIVE", description: "\"EXCLUSIVE\"" },
          "exists",
          { type: "literal", value: "EXISTS", description: "\"EXISTS\"" },
          "explain",
          { type: "literal", value: "EXPLAIN", description: "\"EXPLAIN\"" },
          "fail",
          { type: "literal", value: "FAIL", description: "\"FAIL\"" },
          "false",
          { type: "literal", value: "FALSE", description: "\"FALSE\"" },
          "for",
          { type: "literal", value: "FOR", description: "\"FOR\"" },
          "foreign",
          { type: "literal", value: "FOREIGN", description: "\"FOREIGN\"" },
          "from",
          { type: "literal", value: "FROM", description: "\"FROM\"" },
          "glob",
          { type: "literal", value: "GLOB", description: "\"GLOB\"" },
          "group",
          { type: "literal", value: "GROUP", description: "\"GROUP\"" },
          "having",
          { type: "literal", value: "HAVING", description: "\"HAVING\"" },
          "if",
          { type: "literal", value: "IF", description: "\"IF\"" },
          "ignore",
          { type: "literal", value: "IGNORE", description: "\"IGNORE\"" },
          "ilike",
          { type: "literal", value: "ILIKE", description: "\"ILIKE\"" },
          "immediate",
          { type: "literal", value: "IMMEDIATE", description: "\"IMMEDIATE\"" },
          "in",
          { type: "literal", value: "IN", description: "\"IN\"" },
          "index",
          { type: "literal", value: "INDEX", description: "\"INDEX\"" },
          "indexed",
          { type: "literal", value: "INDEXED", description: "\"INDEXED\"" },
          "infinity",
          { type: "literal", value: "INFINITY", description: "\"INFINITY\"" },
          "initially",
          { type: "literal", value: "INITIALLY", description: "\"INITIALLY\"" },
          "inner",
          { type: "literal", value: "INNER", description: "\"INNER\"" },
          "insert",
          { type: "literal", value: "INSERT", description: "\"INSERT\"" },
          "instead",
          { type: "literal", value: "INSTEAD", description: "\"INSTEAD\"" },
          "integer",
          { type: "literal", value: "INTEGER", description: "\"INTEGER\"" },
          "intersect",
          { type: "literal", value: "INTERSECT", description: "\"INTERSECT\"" },
          "into",
          { type: "literal", value: "INTO", description: "\"INTO\"" },
          "is",
          { type: "literal", value: "IS", description: "\"IS\"" },
          "isnull",
          { type: "literal", value: "ISNULL", description: "\"ISNULL\"" },
          "join",
          { type: "literal", value: "JOIN", description: "\"JOIN\"" },
          "key",
          { type: "literal", value: "KEY", description: "\"KEY\"" },
          "left",
          { type: "literal", value: "LEFT", description: "\"LEFT\"" },
          "like",
          { type: "literal", value: "LIKE", description: "\"LIKE\"" },
          "limit",
          { type: "literal", value: "LIMIT", description: "\"LIMIT\"" },
          "match",
          { type: "literal", value: "MATCH", description: "\"MATCH\"" },
          "nan",
          { type: "literal", value: "NaN", description: "\"NaN\"" },
          "natural",
          { type: "literal", value: "NATURAL", description: "\"NATURAL\"" },
          "no",
          { type: "literal", value: "NO", description: "\"NO\"" },
          "not",
          { type: "literal", value: "NOT", description: "\"NOT\"" },
          "notnull",
          { type: "literal", value: "NOTNULL", description: "\"NOTNULL\"" },
          "null",
          { type: "literal", value: "NULL", description: "\"NULL\"" },
          "number",
          { type: "literal", value: "NUMBER", description: "\"NUMBER\"" },
          "of",
          { type: "literal", value: "OF", description: "\"OF\"" },
          "offset",
          { type: "literal", value: "OFFSET", description: "\"OFFSET\"" },
          "on",
          { type: "literal", value: "ON", description: "\"ON\"" },
          "or",
          { type: "literal", value: "OR", description: "\"OR\"" },
          "order",
          { type: "literal", value: "ORDER", description: "\"ORDER\"" },
          "outer",
          { type: "literal", value: "OUTER", description: "\"OUTER\"" },
          "plan",
          { type: "literal", value: "PLAN", description: "\"PLAN\"" },
          "pragma",
          { type: "literal", value: "PRAGMA", description: "\"PRAGMA\"" },
          "primary",
          { type: "literal", value: "PRIMARY", description: "\"PRIMARY\"" },
          "query",
          { type: "literal", value: "QUERY", description: "\"QUERY\"" },
          "raise",
          { type: "literal", value: "RAISE", description: "\"RAISE\"" },
          "references",
          { type: "literal", value: "REFERENCES", description: "\"REFERENCES\"" },
          "regexp",
          { type: "literal", value: "REGEXP", description: "\"REGEXP\"" },
          "reindex",
          { type: "literal", value: "REINDEX", description: "\"REINDEX\"" },
          "release",
          { type: "literal", value: "RELEASE", description: "\"RELEASE\"" },
          "rename",
          { type: "literal", value: "RENAME", description: "\"RENAME\"" },
          "replace",
          { type: "literal", value: "REPLACE", description: "\"REPLACE\"" },
          "restrict",
          { type: "literal", value: "RESTRICT", description: "\"RESTRICT\"" },
          "rollback",
          { type: "literal", value: "ROLLBACK", description: "\"ROLLBACK\"" },
          "row",
          { type: "literal", value: "ROW", description: "\"ROW\"" },
          "savepoint",
          { type: "literal", value: "SAVEPOINT", description: "\"SAVEPOINT\"" },
          "select",
          { type: "literal", value: "SELECT", description: "\"SELECT\"" },
          "set",
          { type: "literal", value: "SET", description: "\"SET\"" },
          "similar",
          { type: "literal", value: "SIMILAR", description: "\"SIMILAR\"" },
          "string",
          { type: "literal", value: "STRING", description: "\"STRING\"" },
          "table",
          { type: "literal", value: "TABLE", description: "\"TABLE\"" },
          "temp",
          { type: "literal", value: "TEMP", description: "\"TEMP\"" },
          "temporary",
          { type: "literal", value: "TEMPORARY", description: "\"TEMPORARY\"" },
          "then",
          { type: "literal", value: "THEN", description: "\"THEN\"" },
          "to",
          { type: "literal", value: "TO", description: "\"TO\"" },
          "transaction",
          { type: "literal", value: "TRANSACTION", description: "\"TRANSACTION\"" },
          "trigger",
          { type: "literal", value: "TRIGGER", description: "\"TRIGGER\"" },
          "true",
          { type: "literal", value: "TRUE", description: "\"TRUE\"" },
          "union",
          { type: "literal", value: "UNION", description: "\"UNION\"" },
          "unique",
          { type: "literal", value: "UNIQUE", description: "\"UNIQUE\"" },
          "update",
          { type: "literal", value: "UPDATE", description: "\"UPDATE\"" },
          "using",
          { type: "literal", value: "USING", description: "\"USING\"" },
          "vacuum",
          { type: "literal", value: "VACUUM", description: "\"VACUUM\"" },
          "values",
          { type: "literal", value: "VALUES", description: "\"VALUES\"" },
          "view",
          { type: "literal", value: "VIEW", description: "\"VIEW\"" },
          "virtual",
          { type: "literal", value: "VIRTUAL", description: "\"VIRTUAL\"" },
          "when",
          { type: "literal", value: "WHEN", description: "\"WHEN\"" },
          "where",
          { type: "literal", value: "WHERE", description: "\"WHERE\"" }
        ],

        peg$bytecode = [
          peg$decode("7)"),
          peg$decode("87\u0107*/ \"7\xDD*) \"7\xEE*# \"7\xA39*\" 3 "),
          peg$decode("8! #7!+&$,#&7!\"\"\" \"+\x8B$!7_+7$74+-%7`+#%'#%$## \"$\"# \"\"# \"*V \"!7_+K$74+A%7U+7%74+-%7`+#%'%%$%# \"$$# \"$## \"$\"# \"\"# \"*# \" $+#%'\"%$\"# \"\"# \"9*\" 3!"),
          peg$decode("8!7\xAE+\x8D$7\x83+\x83%7_+y%7\x83+o%7)+e%7\x83+[%7\xA4+Q%7\x83+G%7\"+=%7\x83+3%7`+)%4+6&+\"&\"%$+# \"$*# \"$)# \"$(# \"$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \"9*\" 3%"),
          peg$decode("!7\xEB+=$7\x83+3%7$+)%4#6'#\"\" %$## \"$\"# \"\"# \"*# \"7~"),
          peg$decode("!7$+\x8D$ #!7\x83+A$7\xA2+7%7\x83+-%7$+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x83+A$7\xA2+7%7\x83+-%7$+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \""),
          peg$decode("!7%+\x8D$ #!7\x83+A$7\xF2+7%7\x83+-%7%+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x83+A$7\xF2+7%7\x83+-%7%+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \""),
          peg$decode("8!7\xE6+<$7\x83+2%7)+(%4#6*#! %$## \"$\"# \"\"# \"9*\" 3)"),
          peg$decode("87&9*\" 3+"),
          peg$decode("7'*# \"7("),
          peg$decode("87\x98*) \"7\x99*# \"7\x9A9*\" 3,"),
          peg$decode("87>*A \"7?*; \"7E*5 \"7E*/ \"7u*) \"7v*# \"7*9*\" 3-"),
          peg$decode("!!7\x8F+' 4!6.!! %+\x97$ #!7\x83+F$7U+<%7\x83+2%7\x8F+(%4$6.$! %$$# \"$## \"$\"# \"\"# \",Q&!7\x83+F$7U+<%7\x83+2%7\x8F+(%4$6.$! %$$# \"$## \"$\"# \"\"# \"\"+)%4\"6/\"\"! %$\"# \"\"# \""),
          peg$decode("!7_+;$7\x83+1%7`+'%4#60# %$## \"$\"# \"\"# \"*\xAD \"!7_+P$7\x83+F%7,+<%7\x83+2%7`+(%4%61%!\"%$%# \"$$# \"$## \"$\"# \"\"# \"*o \"!7_+d$7\x83+Z%7,+P%7\x83+F%7U+<%7\x83+2%7`+(%4'61'!$%$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \""),
          peg$decode("8!7=+P$7\x83+F%7_+<%7\x83+2%7`+(%4%63%!$%$%# \"$$# \"$## \"$\"# \"\"# \"*p \"!7=+e$7\x83+[%7_+Q%7\x83+G%7,+=%7\x83+3%7`+)%4'64'\"&\"%$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \"9*\" 32"),
          peg$decode("7A*y \"7#*s \"7.*m \"7=*g \"7+*a \"!7_+P$7\x83+F%7(+<%7\x83+2%7`+(%4%65%!\"%$%# \"$$# \"$## \"$\"# \"\"# \"*# \"7-"),
          peg$decode("06\"\"1!37"),
          peg$decode("08\"\"1!39"),
          peg$decode("!.:\"\"2:3;+& 4!6<! %*D \"!71+9$ #70,#&70\"+'%4\"6=\" %$\"# \"\"# \""),
          peg$decode("/>\"\"1!3?"),
          peg$decode("!0@\"\"1!3A*# \" $+<$ #70+&$,#&70\"\"\" \"+#%'\"%$\"# \"\"# \""),
          peg$decode("!73+-$74+#%'\"%$\"# \"\"# \""),
          peg$decode("!72+S$7T+I% #70,#&70\"+7%75*# \" $+'%4$6B$ %$$# \"$## \"$\"# \"\"# \"*\x80 \"!7T+P$ #70+&$,#&70\"\"\" \"+7%75*# \" $+'%4#6B# %$## \"$\"# \"\"# \"*B \"!72+7$75*# \" $+'%4\"6C\" %$\"# \"\"# \""),
          peg$decode("0D\"\"1!3E"),
          peg$decode("!/F\"\"1\"3G+G$! #77+&$,#&77\"\"\" \"+! (%+(%4\"6H\"! %$\"# \"\"# \""),
          peg$decode("-\"\"1!3I"),
          peg$decode("0J\"\"1!3K"),
          peg$decode("7:*) \"7V*# \"70"),
          peg$decode("8!7:+;$ #7;,#&7;\"+)%4\"6M\"\"! %$\"# \"\"# \"9*\" 3L"),
          peg$decode("!!87w9*$$\"\" N\"# \"+2$7<+(%4\"6O\"! %$\"# \"\"# \""),
          peg$decode("8!78+F$!87:*# \"709*$$\"\" N\"# \"+(%4\"6Q\"!!%$\"# \"\"# \"*Q \"!76+F$!87:*# \"709*$$\"\" N\"# \"+(%4\"6Q\"!!%$\"# \"\"# \"9*\" 3P"),
          peg$decode("87\xD8*# \"7\xE89*\" 3R"),
          peg$decode(".S\"\"2S3T"),
          peg$decode("8!7a+D$ #7B,#&7B\"+2%7b+(%4#6V#!!%$## \"$\"# \"\"# \"9*\" 3U"),
          peg$decode("!!87b*) \"7@*# \"7\x819*$$\"\" N\"# \"+1$79+'%4\"6W\" %$\"# \"\"# \"*C \"!7@+2$7I+(%4\"6X\"! %$\"# \"\"# \"*# \"7H"),
          peg$decode(".Y\"\"2Y3Z"),
          peg$decode(".[\"\"2[3\\"),
          peg$decode("8!7C+D$ #7F,#&7F\"+2%7C+(%4#6^#!!%$## \"$\"# \"\"# \"*O \"!7D+D$ #7G,#&7G\"+2%7D+(%4#6^#!!%$## \"$\"# \"\"# \"9*\" 3]"),
          peg$decode("!!87C*) \"7@*# \"7\x819*$$\"\" N\"# \"+1$79+'%4\"6W\" %$\"# \"\"# \"*C \"!7@+2$7I+(%4\"6X\"! %$\"# \"\"# \"*# \"7H"),
          peg$decode("!!87D*) \"7@*# \"7\x819*$$\"\" N\"# \"+1$79+'%4\"6W\" %$\"# \"\"# \"*C \"!7@+2$7I+(%4\"6X\"! %$\"# \"\"# \"*# \"7H"),
          peg$decode("!7@+1$7\x82+'%4\"6_\" %$\"# \"\"# \""),
          peg$decode("7J*\\ \"!.:\"\"2:3;+?$!8709*$$\"\" N\"# \"+'%4\"6`\" %$\"# \"\"# \"*) \"7N*# \"7O"),
          peg$decode("7K*# \"7L"),
          peg$decode("7D*\xB3 \"7C*\xAD \"7@*\xA7 \"!.a\"\"2a3b+& 4!6c! %*\x90 \"!.d\"\"2d3e+& 4!6f! %*y \"!.g\"\"2g3h+& 4!6i! %*b \"!.j\"\"2j3k+& 4!6l! %*K \"!.m\"\"2m3n+& 4!6o! %*4 \"!.p\"\"2p3q+& 4!6r! %"),
          peg$decode("!!87M*# \"7\x819*$$\"\" N\"# \"+1$79+'%4\"6W\" %$\"# \"\"# \""),
          peg$decode("7K*; \"70*5 \".s\"\"2s3t*) \".u\"\"2u3v"),
          peg$decode("!.s\"\"2s3t+M$!!77+-$77+#%'\"%$\"# \"\"# \"+! (%+(%4\"6w\"! %$\"# \"\"# \""),
          peg$decode("!.u\"\"2u3v+a$!!77+A$77+7%77+-%77+#%'$%$$# \"$## \"$\"# \"\"# \"+! (%+(%4\"6w\"! %$\"# \"\"# \""),
          peg$decode("87R*# \"7Q9*\" 3x"),
          peg$decode("!7o+{$ #!!87\x819*$$\"\" N\"# \"+-$79+#%'\"%$\"# \"\"# \",F&!!87\x819*$$\"\" N\"# \"+-$79+#%'\"%$\"# \"\"# \"\"+#%'\"%$\"# \"\"# \""),
          peg$decode("!7p+\x85$ #!!87q9*$$\"\" N\"# \"+-$79+#%'\"%$\"# \"\"# \",F&!!87q9*$$\"\" N\"# \"+-$79+#%'\"%$\"# \"\"# \"\"+-%7q+#%'#%$## \"$\"# \"\"# \""),
          peg$decode("!7p+\x91$ #!!87q*# \"7\x819*$$\"\" N\"# \"+-$79+#%'\"%$\"# \"\"# \",L&!!87q*# \"7\x819*$$\"\" N\"# \"+-$79+#%'\"%$\"# \"\"# \"\"+-%7q+#%'#%$## \"$\"# \"\"# \""),
          peg$decode(".y\"\"2y3z"),
          peg$decode(".{\"\"2{3|"),
          peg$decode(".}\"\"2}3~"),
          peg$decode(".\"\"23\x80"),
          peg$decode(".\x81\"\"2\x813\x82"),
          peg$decode(".\x83\"\"2\x833\x84"),
          peg$decode(".\x85\"\"2\x853\x86"),
          peg$decode(".\x87\"\"2\x873\x88"),
          peg$decode(".\x89\"\"2\x893\x8A"),
          peg$decode(".\x8B\"\"2\x8B3\x8C"),
          peg$decode(".\x8D\"\"2\x8D3\x8E"),
          peg$decode(".\x8F\"\"2\x8F3\x90"),
          peg$decode(".\x91\"\"2\x913\x92"),
          peg$decode(".\x93\"\"2\x933\x94"),
          peg$decode(".\x95\"\"2\x953\x96"),
          peg$decode(".\x97\"\"2\x973\x98"),
          peg$decode(".\x99\"\"2\x993\x9A"),
          peg$decode(".\x9B\"\"2\x9B3\x9C"),
          peg$decode(".\x9D\"\"2\x9D3\x9E"),
          peg$decode(".\x9F\"\"2\x9F3\xA0"),
          peg$decode(".\xA1\"\"2\xA13\xA2"),
          peg$decode(".\xA3\"\"2\xA33\xA4"),
          peg$decode(".\xA5\"\"2\xA53\xA6"),
          peg$decode(".\xA7\"\"2\xA73\xA8"),
          peg$decode(".\x87\"\"2\x873\x88"),
          peg$decode(".\xA9\"\"2\xA93\xAA"),
          peg$decode(" #0\xAB\"\"1!3\xAC,)&0\xAB\"\"1!3\xAC\""),
          peg$decode(".\xAD\"\"2\xAD3\xAE*# \"7X"),
          peg$decode(".\xAF\"\"2\xAF3\xB0"),
          peg$decode(".\xB1\"\"2\xB13\xB2"),
          peg$decode("! #-\"\"1!3I,(&-\"\"1!3I\"+A$!8.\xB1\"\"2\xB13\xB29+$$\"# N\"\" \"+#%'\"%$\"# \"\"# \""),
          peg$decode(" \xB3"),
          peg$decode("7\xA2*\xA1 \"7\xA4*\x9B \"7\xA9*\x95 \"7\xAA*\x8F \"7\xAD*\x89 \"7\xAE*\x83 \"7\xC2*} \"7\xC3*w \"7\xC4*q \"7\xC7*k \"7\xCD*e \"7\xD1*_ \"7\xD5*Y \"7\xE0*S \"7\xE1*M \"7\xE5*G \"7\xEB*A \"7\xEC*; \"7\xF2*5 \"7\u010B*/ \"7\u010C*) \"7\u0118*# \"7\u0119"),
          peg$decode("8!7\xED+& 4!6\xB5! %9*\" 3\xB4"),
          peg$decode("8!7\u010F+& 4!6\xB7! %*. \"!7\xCA+& 4!6\xB8! %9*\" 3\xB6"),
          peg$decode("87t*) \"7u*# \"7v9*\" 3\xB9"),
          peg$decode("7Z*# \"7Y"),
          peg$decode("!7\x93+\x8D$ #!7\x83+A$7x+7%7\x83+-%7\x93+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x83+A$7x+7%7\x83+-%7\x93+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \""),
          peg$decode("8.\xBB\"\"2\xBB3\xBC*) \".\xBD\"\"2\xBD3\xBE9*\" 3\xBA"),
          peg$decode("!7y+\x8D$ #!7\x83+A$7z+7%7\x83+-%7y+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x83+A$7z+7%7\x83+-%7y+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \""),
          peg$decode("87f*\x81 \"7g*{ \"!!7d+;$!87d9*$$\"\" N\"# \"+#%'\"%$\"# \"\"# \"+! (%*L \"!!7e+;$!87e9*$$\"\" N\"# \"+#%'\"%$\"# \"\"# \"+! (%9*\" 3\xBF"),
          peg$decode("!7{+\x8D$ #!7\x83+A$7|+7%7\x83+-%7{+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x83+A$7|+7%7\x83+-%7{+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \"*# \"7\x8B"),
          peg$decode("!7}+\x8D$ #!7\x83+A$7+7%7\x83+-%7}+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x83+A$7+7%7\x83+-%7}+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \""),
          peg$decode("87j*/ \"7i*) \"7h*# \"7k9*\" 3\xC0"),
          peg$decode("8.\xC2\"\"2\xC23\xC3*Y \".\xC4\"\"2\xC43\xC5*M \".\xC6\"\"2\xC63\xC7*A \".\xC8\"\"2\xC83\xC9*5 \".\xCA\"\"2\xCA3\xCB*) \".\xCC\"\"2\xCC3\xCD9*\" 3\xC1"),
          peg$decode("80\xCF\"\"1!3\xD09*\" 3\xCE"),
          peg$decode("8.\xA9\"\"2\xA93\xAA*M \".\xD2\"\"2\xD23\xD3*A \".\xD4\"\"2\xD43\xD5*5 \".\xD6\"\"2\xD63\xD7*) \".\xD8\"\"2\xD83\xD99*\" 3\xD1"),
          peg$decode(" #7\x80*) \"7\x82*# \"7P,/&7\x80*) \"7\x82*# \"7P\""),
          peg$decode(" #7\x80*# \"7S,)&7\x80*# \"7S\""),
          peg$decode("87\xE1*# \"7\xEC9*\" 3\xDA"),
          peg$decode("!7\x8F+=$7\x83+3%7\x85+)%4#6\xDB#\"\" %$## \"$\"# \"\"# \""),
          peg$decode("!7\x8F+R$7\x83+H%7\xE0+>%7\x83+4%7\x92+*%4%6\xDC%#$\" %$%# \"$$# \"$## \"$\"# \"\"# \""),
          peg$decode("!7\x8F+R$7\x83+H%7\xD5+>%7\x83+4%7)+*%4%6\xDD%#$\" %$%# \"$$# \"$## \"$\"# \"\"# \"*\xCD \"!7\x8F+\xC2$7\x83+\xB8%7\xD5+\xAE%7\x83+\xA4%7_+\x9A% #!7\x8F+7$7U+-%7\x83+#%'#%$## \"$\"# \"\"# \"+E$,B&!7\x8F+7$7U+-%7\x83+#%'#%$## \"$\"# \"\"# \"\"\"\" \"*# \" $+=%7\x83+3%7`+)%4(6\xDE(\"'%%$(# \"$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \""),
          peg$decode("!7\x8F+z$7\x83+p%7\xAA+f%7\x83+\\%7\x8F+R%7\x83+H%7\xA2+>%7\x83+4%7\x8F+*%4)6\xDF)#($ %$)# \"$(# \"$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \""),
          peg$decode("87\xE5*# \"7\xD39*\" 3\xE0"),
          peg$decode("8!7\x8F+q$7\x83+g%7\x8A+]%7\x83+S%7\x8F+I%7\x83+?%7\xC4+5%7E++%4(6\xE1($'%# %$(# \"$'# \"$&# \"$%# \"$$# \"$## \"$\"# \"\"# \"*] \"!7\x8F+R$7\x83+H%7\x8A+>%7\x83+4%7\x8F+*%4%6\xE2%#$\" %$%# \"$$# \"$## \"$\"# \"\"# \"9*\" 3\xE0"),
          peg$decode("7\xFB*B \"!7\u0106+7$7\x83+-%7\u010C+#%'#%$## \"$\"# \"\"# \""),
          peg$decode("8!7\x8F+R$7\x83+H%7\x8C+>%7\x83+4%7\x8F+*%4%6\xE4%#$\" %$%# \"$$# \"$## \"$\"# \"\"# \"9*\" 3\xE3"),
          peg$decode("8!7\xEB+=$7\x83+3%7\x90+)%4#6\xE6#\"\" %$## \"$\"# \"\"# \"9*\" 3\xE5"),
          peg$decode("!7/+\xBF$ #!7\x83+Z$7a+P%7\x83+F%7)+<%7\x83+2%7b+(%4&6\xE7&!\"%$&# \"$%# \"$$# \"$## \"$\"# \"\"# \",e&!7\x83+Z$7a+P%7\x83+F%7)+<%7\x83+2%7b+(%4&6\xE7&!\"%$&# \"$%# \"$$# \"$## \"$\"# \"\"# \"\"+)%4\"6\xE8\"\"! %$\"# \"\"# \""),
          peg$decode("7\x8E*G \"7\x8B*A \"7\x8D*; \"7\x89*5 \"7\x88*/ \"7\x86*) \"7\x87*# \"7\x8F"),
          peg$decode("87Y*) \"7Z*# \"7^9*\" 3\xE9"),
          peg$decode("!7\x91+=$7\x83+3%7\x90+)%4#6\xEA#\"\" %$## \"$\"# \"\"# \"*# \"7\x90"),
          peg$decode("!7\x92+\x8D$ #!7\x83+A$7\x94+7%7\x83+-%7\x92+#%'$%$$# \"$## \"$\"# \"\"# \",L&!7\x83+A$7\x94+7%7\x83+-%7\x92+#%'$%$$# \"$## \"$\"# \"\"# \"\"+)%4\"6(\"\"! %$\"# \"\"# \""),
          peg$decode("87[*) \"7\\*# \"7]9*\" 3\xEB"),
          peg$decode("! #0\xEC\"\"1!3\xED+,$,)&0\xEC\"\"1!3\xED\"\"\" \"+' 4!6\xEE!! %"),
          peg$decode("!!!7=+7$7V+-%7\x95+#%'#%$## \"$\"# \"\"# \"+' 4!6\xEF!! %*/ \"!7\x95+' 4!6\xF0!! %+' 4!6\xF1!! %"),
          peg$decode("!.\xF2\"\"2\xF23\xF3+-$7=+#%'\"%$\"# \"\"# \""),
          peg$decode(".\xF4\"\"2\xF43\xF5"),
          peg$decode(".\xF4\"\"2\xF43\xF5"),
          peg$decode(".\xF4\"\"2\xF43\xF5"),
          peg$decode("/\xF6\"\"1%3\xF7"),
          peg$decode("/\xF8\"\"1&3\xF9"),
          peg$decode("/\xFA\"\"1#3\xFB"),
          peg$decode("/\xFC\"\"1%3\xFD"),
          peg$decode("/\xFE\"\"1#3\xFF"),
          peg$decode("/\u0100\"\"1%3\u0101"),
          peg$decode("/\u0102\"\"1'3\u0103"),
          peg$decode("/\u0104\"\"1#3\u0105"),
          peg$decode("/\u0106\"\"1%3\u0107"),
          peg$decode("/\u0108\"\"1\"3\u0109"),
          peg$decode("/\u010A\"\"1#3\u010B"),
          peg$decode("/\u010C\"\"1&3\u010D"),
          peg$decode("/\u010E\"\"1-3\u010F"),
          peg$decode("/\u0110\"\"1&3\u0111"),
          peg$decode("/\u0112\"\"1%3\u0113"),
          peg$decode("/\u0114\"\"1'3\u0115"),
          peg$decode("/\u0116\"\"1\"3\u0117"),
          peg$decode("/\u0118\"\"1'3\u0119"),
          peg$decode("/\u011A\"\"1$3\u011B"),
          peg$decode("/\u011C\"\"1$3\u011D"),
          peg$decode("/\u011E\"\"1%3\u011F"),
          peg$decode("/\u0120\"\"1'3\u0121"),
          peg$decode("/\u0122\"\"1&3\u0123"),
          peg$decode("/\u0124\"\"1&3\u0125"),
          peg$decode("/\u0126\"\"1(3\u0127"),
          peg$decode("/\u0128\"\"1*3\u0129"),
          peg$decode("!7\x83+3$/\u012A\"\"1&3\u012B+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u012C\"\"1%3\u012D"),
          peg$decode("/\u012E\"\"1(3\u012F"),
          peg$decode("/\u0130\"\"1'3\u0131"),
          peg$decode("/\u0132\"\"1*3\u0133"),
          peg$decode("/\u0134\"\"1(3\u0135"),
          peg$decode("!7\x83+3$/\u0136\"\"1&3\u0137+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u0138\"\"1$3\u0139"),
          peg$decode("/\u013A\"\"1&3\u013B"),
          peg$decode("/\u013C\"\"1(3\u013D"),
          peg$decode("/\u013E\"\"1$3\u013F"),
          peg$decode("/>\"\"1!3\u0140"),
          peg$decode("/\u0141\"\"1$3\u0142"),
          peg$decode("/\u0143\"\"1$3\u0144"),
          peg$decode("/\u0145\"\"1#3\u0146"),
          peg$decode("/\u0147\"\"1&3\u0148"),
          peg$decode("/\u0149\"\"1&3\u014A"),
          peg$decode("/\u014B\"\"1)3\u014C"),
          peg$decode("/\u014D\"\"1&3\u014E"),
          peg$decode("!7\x83+3$/\u014F\"\"1'3\u0150+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u0151\"\"1$3\u0152"),
          peg$decode("/\u0153\"\"1%3\u0154"),
          peg$decode("/\u0155\"\"1#3\u0156"),
          peg$decode("/\u0157\"\"1'3\u0158"),
          peg$decode("/\u0159\"\"1$3\u015A"),
          peg$decode("/\u015B\"\"1$3\u015C"),
          peg$decode("/\u015D\"\"1%3\u015E"),
          peg$decode("/\u015F\"\"1&3\u0160"),
          peg$decode("/\u0161\"\"1\"3\u0162"),
          peg$decode("/\u0163\"\"1&3\u0164"),
          peg$decode("/\u0165\"\"1%3\u0166"),
          peg$decode("/\u0167\"\"1)3\u0168"),
          peg$decode("/\u0169\"\"1\"3\u016A"),
          peg$decode("/\u016B\"\"1%3\u016C"),
          peg$decode("/\u016D\"\"1'3\u016E"),
          peg$decode("/\u016F\"\"1(3\u0170"),
          peg$decode("/\u0171\"\"1)3\u0172"),
          peg$decode("/\u0173\"\"1%3\u0174"),
          peg$decode("!7\x83+3$/\u0175\"\"1&3\u0176+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u0177\"\"1'3\u0178"),
          peg$decode("/\u0179\"\"1'3\u017A"),
          peg$decode("/\u017B\"\"1)3\u017C"),
          peg$decode("/\u017D\"\"1$3\u017E"),
          peg$decode("/\u017F\"\"1\"3\u0180"),
          peg$decode("/\u0181\"\"1&3\u0182"),
          peg$decode("/\u0183\"\"1$3\u0184"),
          peg$decode("/\u0185\"\"1#3\u0186"),
          peg$decode("/\u0187\"\"1$3\u0188"),
          peg$decode("/\u0189\"\"1$3\u018A"),
          peg$decode("/\u018B\"\"1%3\u018C"),
          peg$decode("/\u018D\"\"1%3\u018E"),
          peg$decode("/\u018F\"\"1#3\u0190"),
          peg$decode("/\u0191\"\"1'3\u0192"),
          peg$decode("/\u0193\"\"1\"3\u0194"),
          peg$decode("/\u0195\"\"1#3\u0196"),
          peg$decode("/\u0197\"\"1'3\u0198"),
          peg$decode("/\u0199\"\"1$3\u019A"),
          peg$decode("/\u019B\"\"1&3\u019C"),
          peg$decode("/\u019D\"\"1\"3\u019E"),
          peg$decode("/\u019F\"\"1&3\u01A0"),
          peg$decode("/\u01A1\"\"1\"3\u01A2"),
          peg$decode("/\u01A3\"\"1\"3\u01A4"),
          peg$decode("/\u01A5\"\"1%3\u01A6"),
          peg$decode("/\u01A7\"\"1%3\u01A8"),
          peg$decode("/\u01A9\"\"1$3\u01AA"),
          peg$decode("/\u01AB\"\"1&3\u01AC"),
          peg$decode("/\u01AD\"\"1'3\u01AE"),
          peg$decode("/\u01AF\"\"1%3\u01B0"),
          peg$decode("/\u01B1\"\"1%3\u01B2"),
          peg$decode("/\u01B3\"\"1*3\u01B4"),
          peg$decode("/\u01B5\"\"1&3\u01B6"),
          peg$decode("/\u01B7\"\"1'3\u01B8"),
          peg$decode("/\u01B9\"\"1'3\u01BA"),
          peg$decode("/\u01BB\"\"1&3\u01BC"),
          peg$decode("!7\x83+3$/\u01BD\"\"1'3\u01BE+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u01BF\"\"1(3\u01C0"),
          peg$decode("/\u01C1\"\"1(3\u01C2"),
          peg$decode("/\u01C3\"\"1#3\u01C4"),
          peg$decode("/\u01C5\"\"1)3\u01C6"),
          peg$decode("!7\x83+3$/\u01C7\"\"1&3\u01C8+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u01C9\"\"1#3\u01CA"),
          peg$decode("/\u01CB\"\"1'3\u01CC"),
          peg$decode("/\u01CD\"\"1&3\u01CE"),
          peg$decode("/\u01CF\"\"1%3\u01D0"),
          peg$decode("/\u01D1\"\"1$3\u01D2"),
          peg$decode("/\u01D3\"\"1)3\u01D4"),
          peg$decode("/\u01D5\"\"1$3\u01D6"),
          peg$decode("/\u01D7\"\"1\"3\u01D8"),
          peg$decode("/\u01D9\"\"1+3\u01DA"),
          peg$decode("/\u01DB\"\"1'3\u01DC"),
          peg$decode("/\u01DD\"\"1$3\u01DE"),
          peg$decode("/\u01DF\"\"1%3\u01E0"),
          peg$decode("/\u01E1\"\"1&3\u01E2"),
          peg$decode("!7\x83+3$/\u01E3\"\"1&3\u01E4+#%'\"%$\"# \"\"# \""),
          peg$decode("/\u01E5\"\"1%3\u01E6"),
          peg$decode("/\u01E7\"\"1&3\u01E8"),
          peg$decode("/\u01E9\"\"1&3\u01EA"),
          peg$decode("/\u01EB\"\"1$3\u01EC"),
          peg$decode("/\u01ED\"\"1'3\u01EE"),
          peg$decode("/\u01EF\"\"1$3\u01F0"),
          peg$decode("/\u01F1\"\"1%3\u01F2")
        ],

        peg$currPos          = 0,
        peg$reportedPos      = 0,
        peg$cachedPos        = 0,
        peg$cachedPosDetails = { line: 1, column: 1, seenCR: false },
        peg$maxFailPos       = 0,
        peg$maxFailExpected  = [],
        peg$silentFails      = 0,

        peg$cache = {},
        peg$result;

    if ("startRule" in options) {
      if (!(options.startRule in peg$startRuleIndices)) {
        throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
      }

      peg$startRuleIndex = peg$startRuleIndices[options.startRule];
    }

    function text() {
      return input.substring(peg$reportedPos, peg$currPos);
    }

    function offset() {
      return peg$reportedPos;
    }

    function line() {
      return peg$computePosDetails(peg$reportedPos).line;
    }

    function column() {
      return peg$computePosDetails(peg$reportedPos).column;
    }

    function expected(description) {
      throw peg$buildException(
        null,
        [{ type: "other", description: description }],
        peg$reportedPos
      );
    }

    function error(message) {
      throw peg$buildException(message, null, peg$reportedPos);
    }

    function peg$computePosDetails(pos) {
      function advance(details, startPos, endPos) {
        var p, ch;

        for (p = startPos; p < endPos; p++) {
          ch = input.charAt(p);
          if (ch === "\n") {
            if (!details.seenCR) { details.line++; }
            details.column = 1;
            details.seenCR = false;
          } else if (ch === "\r" || ch === "\u2028" || ch === "\u2029") {
            details.line++;
            details.column = 1;
            details.seenCR = true;
          } else {
            details.column++;
            details.seenCR = false;
          }
        }
      }

      if (peg$cachedPos !== pos) {
        if (peg$cachedPos > pos) {
          peg$cachedPos = 0;
          peg$cachedPosDetails = { line: 1, column: 1, seenCR: false };
        }
        advance(peg$cachedPosDetails, peg$cachedPos, pos);
        peg$cachedPos = pos;
      }

      return peg$cachedPosDetails;
    }

    function peg$fail(expected) {
      if (peg$currPos < peg$maxFailPos) { return; }

      if (peg$currPos > peg$maxFailPos) {
        peg$maxFailPos = peg$currPos;
        peg$maxFailExpected = [];
      }

      peg$maxFailExpected.push(expected);
    }

    function peg$buildException(message, expected, pos) {
      function cleanupExpected(expected) {
        var i = 1;

        expected.sort(function(a, b) {
          if (a.description < b.description) {
            return -1;
          } else if (a.description > b.description) {
            return 1;
          } else {
            return 0;
          }
        });

        while (i < expected.length) {
          if (expected[i - 1] === expected[i]) {
            expected.splice(i, 1);
          } else {
            i++;
          }
        }
      }

      function buildMessage(expected, found) {
        function stringEscape(s) {
          function hex(ch) { return ch.charCodeAt(0).toString(16).toUpperCase(); }

          return s
            .replace(/\\/g,   '\\\\')
            .replace(/"/g,    '\\"')
            .replace(/\x08/g, '\\b')
            .replace(/\t/g,   '\\t')
            .replace(/\n/g,   '\\n')
            .replace(/\f/g,   '\\f')
            .replace(/\r/g,   '\\r')
            .replace(/[\x00-\x07\x0B\x0E\x0F]/g, function(ch) { return '\\x0' + hex(ch); })
            .replace(/[\x10-\x1F\x80-\xFF]/g,    function(ch) { return '\\x'  + hex(ch); })
            .replace(/[\u0180-\u0FFF]/g,         function(ch) { return '\\u0' + hex(ch); })
            .replace(/[\u1080-\uFFFF]/g,         function(ch) { return '\\u'  + hex(ch); });
        }

        var expectedDescs = new Array(expected.length),
            expectedDesc, foundDesc, i;

        for (i = 0; i < expected.length; i++) {
          expectedDescs[i] = expected[i].description;
        }

        expectedDesc = expected.length > 1
          ? expectedDescs.slice(0, -1).join(", ")
              + " or "
              + expectedDescs[expected.length - 1]
          : expectedDescs[0];

        foundDesc = found ? "\"" + stringEscape(found) + "\"" : "end of input";

        return "Expected " + expectedDesc + " but " + foundDesc + " found.";
      }

      var posDetails = peg$computePosDetails(pos),
          found      = pos < input.length ? input.charAt(pos) : null;

      if (expected !== null) {
        cleanupExpected(expected);
      }

      return new SyntaxError(
        message !== null ? message : buildMessage(expected, found),
        expected,
        found,
        pos,
        posDetails.line,
        posDetails.column
      );
    }

    function peg$decode(s) {
      var bc = new Array(s.length), i;

      for (i = 0; i < s.length; i++) {
        bc[i] = s.charCodeAt(i) - 32;
      }

      return bc;
    }

    function peg$parseRule(index) {
      var bc    = peg$bytecode[index],
          ip    = 0,
          ips   = [],
          end   = bc.length,
          ends  = [],
          stack = [],
          params, i;

      var key    = peg$currPos * 250 + index,
          cached = peg$cache[key];

      if (cached) {
        peg$currPos = cached.nextPos;
        return cached.result;
      }

      function protect(object) {
        return Object.prototype.toString.apply(object) === "[object Array]" ? [] : object;
      }

      while (true) {
        while (ip < end) {
          switch (bc[ip]) {
            case 0:
              stack.push(protect(peg$consts[bc[ip + 1]]));
              ip += 2;
              break;

            case 1:
              stack.push(peg$currPos);
              ip++;
              break;

            case 2:
              stack.pop();
              ip++;
              break;

            case 3:
              peg$currPos = stack.pop();
              ip++;
              break;

            case 4:
              stack.length -= bc[ip + 1];
              ip += 2;
              break;

            case 5:
              stack.splice(-2, 1);
              ip++;
              break;

            case 6:
              stack[stack.length - 2].push(stack.pop());
              ip++;
              break;

            case 7:
              stack.push(stack.splice(stack.length - bc[ip + 1], bc[ip + 1]));
              ip += 2;
              break;

            case 8:
              stack.pop();
              stack.push(input.substring(stack[stack.length - 1], peg$currPos));
              ip++;
              break;

            case 9:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (stack[stack.length - 1]) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 10:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (stack[stack.length - 1] === peg$FAILED) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 11:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (stack[stack.length - 1] !== peg$FAILED) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 12:
              if (stack[stack.length - 1] !== peg$FAILED) {
                ends.push(end);
                ips.push(ip);

                end = ip + 2 + bc[ip + 1];
                ip += 2;
              } else {
                ip += 2 + bc[ip + 1];
              }

              break;

            case 13:
              ends.push(end);
              ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

              if (input.length > peg$currPos) {
                end = ip + 3 + bc[ip + 1];
                ip += 3;
              } else {
                end = ip + 3 + bc[ip + 1] + bc[ip + 2];
                ip += 3 + bc[ip + 1];
              }

              break;

            case 14:
              ends.push(end);
              ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

              if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length) === peg$consts[bc[ip + 1]]) {
                end = ip + 4 + bc[ip + 2];
                ip += 4;
              } else {
                end = ip + 4 + bc[ip + 2] + bc[ip + 3];
                ip += 4 + bc[ip + 2];
              }

              break;

            case 15:
              ends.push(end);
              ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

              if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length).toLowerCase() === peg$consts[bc[ip + 1]]) {
                end = ip + 4 + bc[ip + 2];
                ip += 4;
              } else {
                end = ip + 4 + bc[ip + 2] + bc[ip + 3];
                ip += 4 + bc[ip + 2];
              }

              break;

            case 16:
              ends.push(end);
              ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

              if (peg$consts[bc[ip + 1]].test(input.charAt(peg$currPos))) {
                end = ip + 4 + bc[ip + 2];
                ip += 4;
              } else {
                end = ip + 4 + bc[ip + 2] + bc[ip + 3];
                ip += 4 + bc[ip + 2];
              }

              break;

            case 17:
              stack.push(input.substr(peg$currPos, bc[ip + 1]));
              peg$currPos += bc[ip + 1];
              ip += 2;
              break;

            case 18:
              stack.push(peg$consts[bc[ip + 1]]);
              peg$currPos += peg$consts[bc[ip + 1]].length;
              ip += 2;
              break;

            case 19:
              stack.push(peg$FAILED);
              if (peg$silentFails === 0) {
                peg$fail(peg$consts[bc[ip + 1]]);
              }
              ip += 2;
              break;

            case 20:
              peg$reportedPos = stack[stack.length - 1 - bc[ip + 1]];
              ip += 2;
              break;

            case 21:
              peg$reportedPos = peg$currPos;
              ip++;
              break;

            case 22:
              params = bc.slice(ip + 4, ip + 4 + bc[ip + 3]);
              for (i = 0; i < bc[ip + 3]; i++) {
                params[i] = stack[stack.length - 1 - params[i]];
              }

              stack.splice(
                stack.length - bc[ip + 2],
                bc[ip + 2],
                peg$consts[bc[ip + 1]].apply(null, params)
              );

              ip += 4 + bc[ip + 3];
              break;

            case 23:
              stack.push(peg$parseRule(bc[ip + 1]));
              ip += 2;
              break;

            case 24:
              peg$silentFails++;
              ip++;
              break;

            case 25:
              peg$silentFails--;
              ip++;
              break;

            default:
              throw new Error("Invalid opcode: " + bc[ip] + ".");
          }
        }

        if (ends.length > 0) {
          end = ends.pop();
          ip = ips.pop();
        } else {
          break;
        }
      }

      peg$cache[key] = { nextPos: peg$currPos, result: stack[0] };

      return stack[0];
    }


      //var unroll = options.util.makeUnroll(line, column, offset, SyntaxError)
      //var ast    = options.util.makeAST(line, column, offset, options)

      // Header/utility functions for grammar match bodies.
      //

      function extractOptional(optional, index) {
        return optional ? optional[index] : null;
      }

      function extractList(list, index) {
        var result = new Array(list.length), i;

        for (i = 0; i < list.length; i++) {
          result[i] = list[i][index];
        }

        return result;
      }

      function buildList(first, rest, index) {
        return [first].concat(extractList(rest, index));
      }

      function buildTree(first, rest, builder) {
        var result = first, i;

        for (i = 0; i < rest.length; i++) {
          result = builder(result, rest[i]);
        }

        return result;
      }

      function buildBinaryExpression(first, rest) {
        return buildTree(first, rest, function(result, element) {
          return {
            type:     "BinaryExpression",
            operator: element[1],
            left:     result,
            right:    element[3]
          };
        });
      }

      function optionalList(value) {
        return value !== null ? value : [];
      }


    peg$result = peg$parseRule(peg$startRuleIndex);

    if (peg$result !== peg$FAILED && peg$currPos === input.length) {
      return peg$result;
    } else {
      if (peg$result !== peg$FAILED && peg$currPos < input.length) {
        peg$fail({ type: "end", description: "end of input" });
      }

      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
    }
  }

  return {
    SyntaxError: SyntaxError,
    parse:       parse
  };
})();